Generating Test Data through Integration Tests
scikit-hep/awkward pull request #1044
Opened 2021-08-02 20:59 UTC by SantamRC

To execute run,
`python print-data.py`

Progress:

- [ ] Reducer.cpp
- [ ] Slice,cpp
- [ ] Index.cpp
- [ ] Identities.cpp
- [ ] Content.cpp
- [ ] Files in layoutbuilder
- [ ] Files in array

2021-08-16 06:09 UTC, ianna requested changes
please, make sure the branch is up-to-date with your local changes. Thanks!

2021-08-16 06:09 UTC, ianna commented on print-data.py
> +            new_file += '\tstd::cout<<"awkward_Index_to_Index64:";for(int i=0;i<length();i++){std::cout <<ptr()[i]<<",";}std::cout<<":";printMe();std::cout<<":"<<length_<<std::endl;\n'
@SantamRC - have you updated the PR? This line gives numerous  compilation errors:
```
/Users/yana/Projects/IRIS-Fellow/Santam/new-plan/awkward-1.0/src/libawkward/Index.cpp:294:81: error: type 'std::shared_ptr<int64_t>' (aka 'shared_ptr<long long>') does not provide a call operator
        std::cout<<"awkward_Index_to_Index64:";for(int i=0;i<length();i++){std::cout <<ptr()[i]<<",";}std::cout<<":";printMe();std::cout<<":"<<length_<<std::endl;
                                                                                       ^~~
```

2021-09-03 14:07 UTC, ianna commented
@SantamRC - are you still working on this PR? Please, close it if not. Thanks!

2021-09-03 14:13 UTC, SantamRC commented
@ianna I am working on getting the data for the remaining kernel functions right now. Using this PR for it. Will close after it's done.

2021-09-07 22:03 UTC, closed without merging