modified the implementation of GrowableBuffer to use multiple Panels
scikit-hep/awkward pull request #1479
Opened 2022-05-25 15:08 UTC by ManasviGoyal

Modified the implementation of GrowableBuffer to use multiple Panels. I have made changes to the following files -
- include/awkward/builder/GrowableBuffer.h
- src/libawkward/builder/GrowableBuffer.cpp

2022-05-25 16:02 UTC, ianna requested changes
Great! It's a good start. Thanks. Please, see my comments inlined. I think, you can use a raw pointer for now `Panel<T>* ptr_;` instead of `unique_ptr<T> ptr_;`. Then wrap it as unique later. There are a few minor comments about style. Thanks!

2022-05-25 16:02 UTC, ianna commented on include/awkward/builder/GrowableBuffer.h
> +    class Panel_Node {
it's better to call it `PanelNode` to keep the style. The class should be private.

2022-05-25 16:02 UTC, ianna commented on include/awkward/builder/GrowableBuffer.h
> +    class Panel {
I don't think you need this class, because the GrowableBuffer itself can allocate and keep track of new panels.

2022-05-25 16:02 UTC, ianna commented on include/awkward/builder/GrowableBuffer.h
> +    class Panel {
Then, actually a `PanelNode` can be named a `Panel `:-)

2022-05-25 16:02 UTC, ianna commented on include/awkward/builder/GrowableBuffer.h
> +      size_t panels_;
so all these methods and members become private methods and private members of the `GrowableBuffer`

2022-05-25 16:02 UTC, ianna commented on src/libawkward/builder/GrowableBuffer.cpp
> +      new (head_) Panel_Node(reserved);
I think, all you need it to instantiate a `Panel` and update the `GrowableBuffer` pointer. Should it be done in the `append` method of the GrowableBuffer?

2022-05-25 16:02 UTC, ianna commented on src/libawkward/builder/GrowableBuffer.cpp
> +  GrowableBuffer<T>::Panel::add_panel(size_t reserved) {
it should be `GrowableBuffer<T>::add_panel(size_t reserved)`

2022-05-25 16:02 UTC, ianna commented on src/libawkward/builder/GrowableBuffer.cpp
> +    tail_->next_ = new_Panel;
`tail_->next_ = new Panel(reserved);`

2022-05-25 16:15 UTC, ManasviGoyal commented
> Great! It's a good start. Thanks. Please, see my comments inlined. I think, you can use a raw pointer for now `Panel<T>* ptr_;` instead of `unique_ptr<T> ptr_;`. Then wrap it as unique later. There are a few minor comments about style. Thanks!

Sure. I'll make the required changes. Thank you.

2022-06-30 12:58 UTC, jpivarski commented
Question: is this superseded by #1494? If so, let's close this PR. Thanks!

2022-06-30 13:02 UTC, ManasviGoyal commented
> Question: is this superseded by #1494? If so, let's close this PR. Thanks!

Yes. I'll close it.

2022-06-30 13:02 UTC, closed without merging