Adding a Forth Based Avro Reader
scikit-hep/awkward pull request #1491
Opened 2022-06-06 18:04 UTC by aryan26roy

2022-06-07 18:03 UTC, aryan26roy commented
Some Performance Indicators when compared to uavro:
- avro file with records of 3 floats (~100Mb) : uavro- 1.645 s, forth- 0.717 s
- avro file with records of 46 floats (~90 Mb) : uavro- 1.244 s, forth- 0.490 s

2022-06-07 18:12 UTC, aryan26roy commented
Some performance indicators when compared to fastavro:
- avro file with records of 46 floats (~90 Mb) : fastavro- 3.2529 s, forth- 0.490 s
- avro file with r3 level jagged array of floats (~688 Mb) : fastavro- 22.0425 s, forth- 2.699 s

2022-06-07 19:00 UTC, jpivarski requested changes
We talked in person. Most of the things are names, which will be easy to change.

2022-06-07 19:00 UTC, jpivarski commented on src/awkward/_v2/_connect/avro.py
> +    pass
Internal: should start with underscore.

Should be more descriptive. More like `ReachedEndOfArray`?

2022-06-07 19:00 UTC, jpivarski commented on src/awkward/_v2/_connect/avro.py
> +class read_avro_ft:
Python class names are CapitalCamelCase.

2022-06-07 19:00 UTC, jpivarski commented on src/awkward/_v2/_connect/avro.py
> +        self.blocks = []
Only need the total number, not a list of the number in each block.

2022-06-07 19:00 UTC, jpivarski commented on src/awkward/_v2/_connect/avro.py
> +        self.is_prim = False
Use the whole word, "primitive".

2022-06-07 19:00 UTC, jpivarski commented on src/awkward/_v2/_connect/avro.py
> +        forth_code = header_code + _exec_code1 + "\nloop"
Single format string?

2022-06-07 19:00 UTC, jpivarski commented on src/awkward/_v2/_connect/avro.py
> +        forth_code = header_code + _exec_code1 + "\nloop"
Suggestion:

```python
forth_code = f"""
{header_code}
{init_code}
{exec_code}
"""
```

2022-06-08 20:10 UTC, aryan26roy commented
The latest commit adds proper handling for negative length lists. This slows down the performance on the 3-level jagged array of floats from 2.7 s to 3.2 s. However, this slowdown can be avoided my generating three forth codes, one assuming no negative lengths, another assuming all to be negative lengths and third to halt after encountering the first length. This would (probably) give nearly the same performance as the one without checks.

2022-06-10 14:09 UTC, merged