docs: retested and modernized all the docstrings in highlevel.py.
scikit-hep/awkward pull request #1954
Opened 2022-12-05 23:12 UTC by jpivarski

This finishes the work started in #1946, commit dc0f91e1978ee3f364ed4b3c9abb5181798be99b.

All of the sample code in docstrings is being tested and modernized: `print` statements are being removed in favor of `show` and the output is being replaced with v2 output.

2022-12-05 23:39 UTC, jpivarski commented
100% of these changes are in code snippets in docstrings.

2022-12-05 23:48 UTC, agoose77 requested changes

2022-12-05 23:48 UTC, agoose77 commented on src/awkward/operations/ak_combinations.py
> +        >>> ak.combinations(array, 2, axis=0).show()
This was such a big QoL improvement.

2022-12-05 23:48 UTC, agoose77 commented on src/awkward/operations/ak_count.py
> +        ...                    [30.1, 30.2      ]])
Remove a leading space?
```suggestion
        ...                   [None, 10.2, None],
        ...                   None,
        ...                   [20.1, 20.2, 20.3],
        ...                   [30.1, 30.2      ]])
```

2022-12-05 23:48 UTC, agoose77 commented on src/awkward/operations/ak_to_categorical.py
> +        >>> categorical.tolist() == array.tolist()
Should we promote `to_list` over `tolist`?
```suggestion
        >>> categorical.to_list() == array.to_list()
```

2022-12-05 23:49 UTC, agoose77 commented
You have the go-ahead to merge once you've either changed or ignored the discussion points! :)

2022-12-05 23:59 UTC, jpivarski commented on src/awkward/operations/ak_count.py
> +        ...                    [30.1, 30.2      ]])
Yes, that's right: semantically, the spacing should be one to the left.

2022-12-06 00:01 UTC, jpivarski commented on src/awkward/operations/ak_to_categorical.py
> +        >>> categorical_records.tolist() == records.tolist()
If that's what we're doing, here's another one.

```suggestion
        >>> categorical_records.to_list() == records.to_list()
```

2022-12-06 00:03 UTC, jpivarski commented
@agoose77 I've enabled auto-merge, and only re-requested the review so that you can make it not red. It won't stop the merge.

Thanks!

2022-12-06 00:05 UTC, agoose77 approved these changes

2022-12-06 00:14 UTC, merged