docs: how to accelerate awkward arrays with cppyy
scikit-hep/awkward pull request #2334
Opened 2023-03-22 07:39 UTC by ianna

2023-03-22 13:55 UTC, ianna reviewed
@agoose77 - please, suggest what is the best place for Awkward-cppyy GIT. Thanks.

2023-03-22 13:55 UTC, ianna commented on docs/_toc.yml
> +                        title: "Awkward Arrays acceleration with JIT-compilation in cppyy"
@agoose77 - I'm hesitating between adding the user guide here or...

2023-03-22 13:55 UTC, ianna commented on docs/_toc.yml
> +
...here?

2023-03-22 15:19 UTC, ianna commented on docs/_toc.yml
> +
ok, it should go here

2023-03-22 15:26 UTC, agoose77 commented
@ianna I think creating a new section was a good decision. I've renamed it to `how-to-use-in-cpp`, because I think we should *also* move the `LayoutBuilder` documentation here? If I understand correctly, we should be able to use `LayoutBuilder` *in* cppyy.

2023-03-22 16:59 UTC, jpivarski requested changes
This has the same fix in it as #2335, so it should be merged afterward.

Also, it should be merged after cppyy 3.0.1 is released ([watch this space](https://pypi.org/project/cppyy/)) and converted into Jupytext that gets evaluated along with the other docs (that's the requested change). The rationale is that we shouldn't put documentation out there for a feature that users can't use... without manually installing cppyy from GitHub and compiling it for half an hour...

The escape valve to allow unevaluated ipynb docs should only be used for GPU docs, since they _have to_ avoid the normal mechanism. For a library that isn't released yet, we can just wait for it to be released. This PR will be easy to merge when that happens.

2023-11-12 23:29 UTC, agoose77 commented
Well, that took some figuring out. I wrote a build script to run inside a `manylinux` container, which is used to generate the cppyy wheels. This allows to build a[ separate container that acts as a binary store for the built wheels](https://github.com/agoose77/cppyy-build-container), which are then extracted in our CI and installed.

For the tests, we install the wheels in a dedicated non-ROOT cppyy job. For the docs, we have a dedicated build-the-cppyy-notebook job that does a similar thing.

This is a somewhat ugly procedure: I'd prefer to push the wheels to a PyPI registry, but off the top of my head I can't think of any non PyPI-registries that we can easily use (though we could push to an AWS bucket).

Once `cppyy` is released, we should remove this monstrosity.

2023-11-13 08:51 UTC, ianna reviewed
@agoose77 - thanks for looking into it! I've already forgotten about this PR :-)

2023-11-13 18:10 UTC, agoose77 commented
@jpivarski I've added a new section to the user guide:

![image](https://github.com/scikit-hep/awkward/assets/1248413/dccc9c3b-b975-4eff-b207-28713f6a41ef)


I've not renamed the actual file for the existing LayoutBuilder docs; this means that we don't need to rewrite the URLs for existing hyperlinks in the wild.

2023-11-13 20:46 UTC, jpivarski approved these changes
Fantastic! We're in a slightly odd position of having documentation for this feature and testing it in CI, but users still can't install the right version of cppyy to use it. I noticed that my comment holding it back was waiting on cppyy 3.0.1 since March. But let's get the documentation out now so that it's ready when cppyy is.

When the easily installable version of cppyy does come out, though, we'll want to use that. Perhaps it won't have these warning messages...

<img width="713" alt="image" src="https://github.com/scikit-hep/awkward/assets/1852447/71d6fbb8-18e6-4499-848b-9b6132731efa">

This is ready to merge, though, as-is.

2023-11-13 20:46 UTC, jpivarski commented on docs/user-guide/how-to-use-in-cpp-cppyy.ipynb
> +    ":::\n",
These warnings are essential. It's a good thing they're there.

2023-11-13 20:46 UTC, jpivarski commented on docs/user-guide/how-to-use-in-cpp-cppyy.ipynb
> +    ":::\n",
<img width="713" alt="image" src="https://github.com/scikit-hep/awkward/assets/1852447/5a79b3dc-5cfe-4fd9-a273-c218b6a572d6">

2023-11-14 10:31 UTC, merged