[WIP] replace carry with indexedarray
scikit-hep/awkward pull request #261
Opened 2020-05-12 12:00 UTC by ianna

Address issue #204 

Following a discussion with @jpivarski to finish what @Ellipse0934 has started in https://github.com/scikit-hep/awkward-1.0/pull/214

2020-05-12 14:55 UTC, ianna commented
@jpivarski - it looks like the Identities get truncated...
```python
        content1 = awkward1.layout.NumpyArray(numpy.array([1, 2, 3, 4, 5]))
        content2 = awkward1.layout.NumpyArray(numpy.array([1.1, 2.2, 3.3, 4.4, 5.5, 6.6, 7.7, 8.8, 9.9]))
        offsets = awkward1.layout.Index64(numpy.array([0, 3, 3, 5, 6, 9]))
        listoffsetarray = awkward1.layout.ListOffsetArray64(offsets, content2)
    
        recordarray = awkward1.layout.RecordArray({"one": content1, "two": listoffsetarray})
        recordarray2 = awkward1.layout.RecordArray({"outer": awkward1.layout.RegularArray(recordarray, 1)})
        recordarray2.setidentities()
        assert recordarray2["outer"].identities.fieldloc == [(0, "outer")]
>       assert recordarray2["outer", 0, "one"].identities.fieldloc == [(0, "outer"), (1, "one")]
E       AssertionError: assert [(0, 'outer')] == [(0, 'outer'), (1, 'one')]
E         Right contains one more item: (1, 'one')
E         Full diff:
E         - [(0, 'outer')]
E         + [(0, 'outer'), (1, 'one')]

```
Here carry index is:
```xml
<Index64 i="[0]" offset="0" length="1" at="0x7fa648d80fa0"/>
```

that gives the following IndexedArray as an output of the `RecordArray::carry`
```xml
<IndexedArray64>
    <Identities32 ref="4" fieldloc="[]" width="1" offset="0" length="1" at="0x7f9f18d1c8a0"/>
    <index><Index64 i="[2]" offset="0" length="1" at="0x7f9f1a448cf0"/></index>
    <content><RecordArray>
        <Identities32 ref="4" fieldloc="[]" width="1" offset="0" length="5" at="0x7f9f18c3a320"/>
        <field index="0" key="outer">
            <RecordArray>
                <Identities32 ref="4" fieldloc="[(0, 'outer')]" width="1" offset="0" length="5" at="0x7f9f18c3a320"/>
                <field index="0" key="one">
                    <NumpyArray format="l" shape="5" data="1 2 3 4 5" at="0x7f9f1a1559d0">
                        <Identities32 ref="4" fieldloc="[(0, 'outer') (0, 'one')]" width="1" offset="0" length="5" at="0x7f9f18c3a320"/>
                    </NumpyArray>
                </field>
                <field index="1" key="two">
                    <ListOffsetArray64>
                        <Identities32 ref="4" fieldloc="[(0, 'outer') (0, 'two')]" width="1" offset="0" length="5" at="0x7f9f18c3a320"/>
                        <offsets><Index64 i="[0 3 3 5 6 9]" offset="0" length="6" at="0x7f9f1a14b880"/></offsets>
                        <content><NumpyArray format="d" shape="9" data="1.1 2.2 3.3 4.4 5.5 6.6 7.7 8.8 9.9" at="0x7f9f1a12f9d0">
                            <Identities64 ref="5" fieldloc="[(0, 'outer') (0, 'two')]" width="2" offset="0" length="9" at="0x7f9f18c8c950"/>
                        </NumpyArray></content>
                    </ListOffsetArray64>
                </field>
            </RecordArray>
        </field>
    </RecordArray></content>
</IndexedArray64>

```
Here is what it should have been before:
```xml
<RecordArray>
    <Identities32 ref="7" fieldloc="[(0, 'outer')]" width="2" offset="0" length="1" at="0x7fa648d7fd30"/>
    <field index="0" key="one">
        <NumpyArray format="l" shape="1" data="3" at="0x7fa648d7fa40">
            <Identities32 ref="7" fieldloc="[(0, 'outer') (1, 'one')]" width="2" offset="0" length="1" at="0x7fa648d839f0"/>
        </NumpyArray>
    </field>
    <field index="1" key="two">
        <ListArray64>
            <Identities32 ref="7" fieldloc="[(0, 'outer') (1, 'two')]" width="2" offset="0" length="1" at="0x7fa648d83c20"/>
            <starts><Index64 i="[3]" offset="0" length="1" at="0x7fa648d7fa30"/></starts>
            <stops><Index64 i="[5]" offset="0" length="1" at="0x7fa648d83b40"/></stops>
            <content><NumpyArray format="d" shape="9" data="1.1 2.2 3.3 4.4 5.5 6.6 7.7 8.8 9.9" at="0x7fa648d4e5a0">
                <Identities64 ref="8" fieldloc="[(0, 'outer') (1, 'two')]" width="3" offset="0" length="9" at="0x7fa648d653c0"/>
            </NumpyArray></content>
        </ListArray64>
    </field>
</RecordArray>
```

2020-06-16 15:59 UTC, ianna commented
@jpivarski - I think, I'd need to modify the high-level Python functions:
```python
    def test_listarray():
        one = awkward1.Array([[{"x": 1}, {"x": 2}, {"x": 3}], [], [{"x": 4}, {"x": 5}]], check_valid=True)
        two = awkward1.Array([[1.1, 2.2, 3.3], [], [4.4, 5.5]], check_valid=True)
>       assert awkward1.to_list(awkward1.with_field(one, two, "y")) == [[{"x": 1, "y": 1.1}, {"x": 2, "y": 2.2}, {"x": 3, "y": 3.3}], [], [{"x": 4, "y": 4.4}, {"x": 5, "y": 5.5}]]

tests/test_0107-assign-fields-to-records.py:80: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
awkward1/operations/structure.py:453: in with_field
    out = awkward1._util.broadcast_and_apply(
awkward1/_util.py:714: in broadcast_and_apply
    out = apply(broadcast_pack(inputs, isscalar), 0)
awkward1/_util.py:570: in apply
    outcontent = apply(nextinputs, depth + 1)
awkward1/_util.py:614: in apply
    outcontent = apply(nextinputs, depth + 1)
awkward1/_util.py:449: in apply
    return apply([x if not isinstance(x, indexedtypes) else x.project()
awkward1/_util.py:449: in apply
```
```python
>   if (any(isinstance(x, listtypes) for x in inputs) and
        not any(isinstance(x, (awkward1.layout.Content,
                               awkward1.layout.Record)) and
                x.has_virtual_form for x in inputs)):
E               RecursionError: maximum recursion depth exceeded while calling a Python object

awkward1/_util.py:401: RecursionError

```

2020-06-16 16:43 UTC, jpivarski commented
I don't know where the recursion error is, but yes, it should be investigated. Does that test example work in master or is it somehow related to this PR? (If the latter, it's an assumption that broke about what to expect from a given function.)

Oh! It could be `IndexedArray::project`, which should return something with one less level of indexing. On the Python side, `broadcast_and_apply` unwraps arrays to get down to the NumpyArray level (the leaves of the tree) and it unwraps IndexedArrays with `project`. If `project` on the C++ side is calling `carry` on its argument and now `RecordArray::carry` returns a new IndexedArray, then that unwrapping step is oscillating between unwrap and rewrap. `IndexedArray::project`, at least, should eagerly carry, so maybe `carry` needs an eagerness argument to let `IndexedArray::project` force an eager projection in `RecordArray::carry`, whereas it's lazy in most other cases.

If that's it, then the bug (bad assumption) manifested itself on the Python side, but can/should be fixed on the C++ side.

2020-06-17 08:13 UTC, ianna commented
> I don't know where the recursion error is, but yes, it should be investigated. Does that test example work in master or is it somehow related to this PR? (If the latter, it's an assumption that broke about what to expect from a given function.)
> 
> Oh! It could be `IndexedArray::project`, which should return something with one less level of indexing. On the Python side, `broadcast_and_apply` unwraps arrays to get down to the NumpyArray level (the leaves of the tree) and it unwraps IndexedArrays with `project`. If `project` on the C++ side is calling `carry` on its argument and now `RecordArray::carry` returns a new IndexedArray, then that unwrapping step is oscillating between unwrap and rewrap. `IndexedArray::project`, at least, should eagerly carry, so maybe `carry` needs an eagerness argument to let `IndexedArray::project` force an eager projection in `RecordArray::carry`, whereas it's lazy in most other cases.
> 
> If that's it, then the bug (bad assumption) manifested itself on the Python side, but can/should be fixed on the C++ side.

@jpivarski - thanks! An eager projection has fixed this issue.

2020-06-17 08:30 UTC, ianna commented
@jpivarski - Here are two test failures (apart from the commented out segfaulting tests). The second is understandable since a `RecordArray` lazy carry changes the type from `RecordArray` to `IndexedArray`.
```python
==================================================================================== FAILURES ====================================================================================
_______________________________________________________________________________ test_setidentities _______________________________________________________________________________

    def test_setidentities():
        content1 = awkward1.layout.NumpyArray(numpy.array([1, 2, 3, 4, 5]))
        content2 = awkward1.layout.NumpyArray(numpy.array([1.1, 2.2, 3.3, 4.4, 5.5, 6.6, 7.7, 8.8, 9.9]))
        offsets = awkward1.layout.Index64(numpy.array([0, 3, 3, 5, 6, 9]))
        listoffsetarray = awkward1.layout.ListOffsetArray64(offsets, content2)
    
        recordarray = awkward1.layout.RecordArray([content1, listoffsetarray])
        recordarray.setidentities()
    
        recordarray = awkward1.layout.RecordArray({"one": content1, "two": listoffsetarray})
        recordarray.setidentities()
        assert recordarray["one"].identities.fieldloc == [(0, "one")]
        assert recordarray["two"].identities.fieldloc == [(0, "two")]
        assert recordarray["one", 1] == 2
        assert recordarray[1, "one"] == 2
        assert recordarray["two", 2, 1] == 5.5
        assert recordarray[2, "two", 1] == 5.5
    
        recordarray = awkward1.layout.RecordArray({"one": content1, "two": listoffsetarray})
        recordarray2 = awkward1.layout.RecordArray({"outer": recordarray})
        recordarray2.setidentities()
        assert recordarray2["outer"].identities.fieldloc == [(0, "outer")]
        assert recordarray2["outer", "one"].identities.fieldloc == [(0, "outer"), (0, "one")]
        assert recordarray2["outer", "two"].identities.fieldloc == [(0, "outer"), (0, "two")]
        assert recordarray2["outer", "one", 1] == 2
        assert recordarray2["outer", 1, "one"] == 2
        assert recordarray2[1, "outer", "one"] == 2
        assert recordarray2["outer", "two", 2, 1] == 5.5
        assert recordarray2["outer", 2, "two", 1] == 5.5
        assert recordarray2[2, "outer", "two", 1] == 5.5
        with pytest.raises(ValueError) as excinfo:
            recordarray2["outer", "two", 0, 99]
        assert str(excinfo.value).endswith(' with identity [0, "outer", "two"] attempting to get 99, index out of range')
        assert recordarray2.identity == ()
        assert recordarray2[2].identity == (2,)
        assert recordarray2[2, "outer"].identity == (2, "outer")
        assert recordarray2[2, "outer", "two"].identity == (2, "outer", "two")
    
        recordarray = awkward1.layout.RecordArray({"one": content1, "two": listoffsetarray})
        recordarray2 = awkward1.layout.RecordArray({"outer": awkward1.layout.RegularArray(recordarray, 1)})
        recordarray2.setidentities()
        assert recordarray2["outer"].identities.fieldloc == [(0, "outer")]
>       assert recordarray2["outer", 0, "one"].identities.fieldloc == [(0, "outer"), (1, "one")]
E       AssertionError: assert [(0, 'outer')] == [(0, 'outer'), (1, 'one')]
E         Right contains one more item: (1, 'one')
E         Full diff:
E         - [(0, 'outer')]
E         + [(0, 'outer'), (1, 'one')]

tests/test_0025-record-array.py:241: AssertionError
_______________________________________________________________________________ test_single_level ________________________________________________________________________________

    def test_single_level():
        template = awkward1.Array([[{"x": 0.0, "y": []}, {"x": 1.1, "y": [1]}, {"x": 2.2, "y": [2, 2]}], [], [{"x": 3.3, "y": [3, 3, 3]}, {"x": 4.4, "y": [4, 4, 4, 4]}]])
        generator = awkward1.layout.ArrayGenerator(lambda: template, form=template.layout.form, length=3)
        d = {}
        cache = awkward1.layout.ArrayCache(d)
        virtualarray = awkward1.layout.VirtualArray(generator, cache)
    
        a = virtualarray[2]
        assert isinstance(a, awkward1.layout.RecordArray)
        assert len(d) == 1
        assert awkward1.to_list(a) == [{"x": 3.3, "y": [3, 3, 3]}, {"x": 4.4, "y": [4, 4, 4, 4]}]
        d.clear()
    
        a = virtualarray[1:]
        assert isinstance(a, awkward1.layout.VirtualArray)
        assert len(d) == 0
        b = a[1]
        assert isinstance(b, awkward1.layout.RecordArray)
        assert len(d) == 1
        assert awkward1.to_list(b) == [{"x": 3.3, "y": [3, 3, 3]}, {"x": 4.4, "y": [4, 4, 4, 4]}]
        d.clear()
    
        a = virtualarray[[0, 2, 1, 0]]
        assert isinstance(a, awkward1.layout.VirtualArray)
        assert len(d) == 0
        b = a[1]
        assert isinstance(b, awkward1.layout.RecordArray)
        assert len(d) == 1
        assert awkward1.to_list(b) == [{"x": 3.3, "y": [3, 3, 3]}, {"x": 4.4, "y": [4, 4, 4, 4]}]
        d.clear()
    
        a = virtualarray[[False, True, True]]
        assert isinstance(a, awkward1.layout.VirtualArray)
        assert len(d) == 0
        b = a[1]
        assert isinstance(b, awkward1.layout.RecordArray)
        assert len(d) == 1
        assert awkward1.to_list(b) == [{"x": 3.3, "y": [3, 3, 3]}, {"x": 4.4, "y": [4, 4, 4, 4]}]
        d.clear()
    
        a = virtualarray["x"]
        assert isinstance(a, awkward1.layout.VirtualArray)
        assert len(d) == 0
        b = a[2]
        assert isinstance(b, awkward1.layout.NumpyArray)
        assert len(d) == 1
        assert awkward1.to_list(b) == [3.3, 4.4]
        d.clear()
    
        a = virtualarray["y"]
        assert isinstance(a, awkward1.layout.VirtualArray)
        assert len(d) == 0
        b = a[2]
        assert isinstance(b, (awkward1.layout.ListArray64, awkward1.layout.ListOffsetArray64))
        assert len(d) == 1
        assert awkward1.to_list(b) == [[3, 3, 3], [4, 4, 4, 4]]
        d.clear()
    
        a = virtualarray[::2, 1]
>       assert isinstance(a, awkward1.layout.RecordArray)
E       assert False
E        +  where False = isinstance(<IndexedArray64>\n    <index><Index64 i="[1 4]" offset="0" length="2" at="0x7fdd2eda0d30"/></index>\n    <content><Recor...d2f8b6a00"/></content>\n            </ListOffsetArray64>\n        </field>\n    </RecordArray></content>\n</IndexedArray64>, <class 'awkward1._ext.RecordArray'>)
E        +    where <class 'awkward1._ext.RecordArray'> = <module 'awkward1.layout' from '/Users/yana/Projects/PR204/awkward-1.0/awkward1/layout.py'>.RecordArray
E        +      where <module 'awkward1.layout' from '/Users/yana/Projects/PR204/awkward-1.0/awkward1/layout.py'> = awkward1.layout

tests/test_0057-virtual-array.py:343: AssertionError

```

2020-06-17 09:00 UTC, ianna commented
@jpivarski - Here is where we stand so far. The 10 tests that cause a Segmentation fault are commented out, the 3 identity tests give different results - please, see in the commit. One test has been modified to allow a different type:
```python
assert isinstance(a, (awkward1.layout.RecordArray, awkward1.layout.IndexedArray64))
```

2020-06-17 10:33 UTC, jpivarski commented
What specifically do you want me to check?

The Python change you made is very likely right: the output that used to always be RecordArray can now be IndexedArray (whenever the carry is lazy, which is almost always: `IndexedArray::project` being an exception). I guess it would always be IndexedArray64 because new (output) arrays are always 64-bit.

2020-06-17 13:00 UTC, ianna commented
> What specifically do you want me to check?
> 
> The Python change you made is very likely right: the output that used to always be RecordArray can now be IndexedArray (whenever the carry is lazy, which is almost always: `IndexedArray::project` being an exception). I guess it would always be IndexedArray64 because new (output) arrays are always 64-bit.

@jpivarski - Please, review the PR when you have time. I think, I'm done with it for the moment: all but identity tests run fine. I'm not sure what to do with truncated identities and identity fields. Also, I might have overdone on eager carry in `IndexedArray::getitem_* `

2020-06-17 19:44 UTC, jpivarski requested changes
I have a few inline comments about `copy`, which could be better named `must_be_eager` (without changing how it's used) or `allow_lazy` (swapping all true values for false and vice-versa).

About the failing identities test: one of them is simply that the test needs to be updated. The tests operate at the level of layout nodes and you've inserted one new layout node (an IndexedArray), so the test needs to descend one level with `.content` to get to where it was before.

~~The other was an indication of a much deeper issue. In the old implementation, the quantity being tested is a Record, and in the new implementation, it's a one element RecordArray. I didn't follow it all the way back to find out what caused that, but it's somewhere in the `getitem` methods, not Identities-handling.~~

**Edit:** after lots of investigation (trying to make a suitable test-case), I found that I had been testing the wrong thing. Old and new give the same results from `getitem`; they only differ in the Identities. I'm going to leave some of those examples here, anyway.

This calls for a more stringent set of tests. You can start with structures like these:

```python
import awkward1
import numpy
a = awkward1.from_iter([
    {"outer": [{"x": 0, "y": []}, {"x": 1, "y": [1]}, {"x": 2, "y": [1, 2]}]},
    {"outer": []},
    {"outer": [{"x": 3, "y": [1, 2, 3]}, {"x": 4, "y": [1, 2, 3, 4]}]}
], highlevel=False)
a.setidentities()

b = awkward1.from_iter([
    {"outer": {"x": 0, "y": []}},
    {"outer": {"x": 1, "y": [1]}},
    {"outer": {"x": 2, "y": [1, 2]}},
    {"outer": {"x": 3, "y": [1, 2, 3]}},
    {"outer": {"x": 4, "y": [1, 2, 3, 4]}}
], highlevel=False)
b.setidentities()
```

which both have two levels of RecordArrays, but `a` has lists in between.

Outside of this PR, make a lot of selections on this record structure to pick out elements at every level and write assertions for the `awkward1.to_list(...)` of each selection, as well as assertions for the Identities, and then ensure that they get the same results in the PR.

```python
>>> a[2, "outer", 1, "y"]
<NumpyArray format="l" shape="4" data="1 2 3 4" at="0x55cb15b9f100">
    <Identities64 ref="2" fieldloc="[(0, 'outer') (1, 'y')]" width="3" offset="18" length="4" at="0x55cb15849140"/>
</NumpyArray>
>>> assert awkward1.to_list(a[2, "outer", 1, "y"]) == [1, 2, 3, 4]
>>> assert a[2, "outer", 1, "y"].identities.fieldloc == [(0, 'outer'), (1, 'y')]
>>> assert numpy.asarray(a[2, "outer", 1, "y"].identities).tolist() == [
...        [2, 1, 0],
...        [2, 1, 1],
...        [2, 1, 2],
...        [2, 1, 3]
... ]
```

Regardless of the fact that it's just an Identities error, doing these kinds of tests can make the transition a lot safer, and they're also a good example of how to diagnose Identities.

2020-06-17 19:44 UTC, jpivarski commented on include/awkward/Content.h
> +      carry(const Index64& carry, bool copy = false) const = 0;
The word "copy" is unclear—whether this parameter is true or false, the `carry` operation doesn't exactly copy anything (make a new buffer in memory that is identical to the old one).

The real distinction is between eagerness, the old behavior on all Content subclasses and the current behavior on all but one (RecordArray), and laziness, the new behavior on RecordArray. It's a question of whether the integer array will be immediately used to rearrange/drop/duplicate elements (regardless of whether the new array eventually gets used for anything) versus adding an IndexedArray node to rearrange/drop/duplicate when it is actually used (and every time it gets used; there are trade-offs either way).

Given that the default value for this parameter is `false`, it could perhaps be named `must_be_eager`. If you're willing to swap all the arguments (true ↔ false), then it could be named `allow_lazy` with a default of true. I find it easier to wrap my head around "allow lazy" than "must be eager." What do you think?

Currently, only RecordArray accepts the parameter's offer to be lazy, but it's possible that others might in the future.

2020-06-17 19:44 UTC, jpivarski commented on include/awkward/array/RawArray.h
> +        return carry(nextcarry, true);
Why does RawArray differ from the default `must_be_eager`? It has no children and doesn't have a laziness definition, anyway.

2020-06-17 19:44 UTC, jpivarski commented on include/awkward/array/RawArray.h
> +      return carry(flathead, true);
Why does RawArray differ from the default `must_be_eager`? It has no children and doesn't have a laziness definition, anyway.

2020-06-17 19:44 UTC, jpivarski commented on tests/test_0025-record-array.py
> +    assert recordarray2["outer", 0, "two"].identities.fieldloc == [(0, 'outer')] ### [(0, "outer"), (1, "two")]
The issue is that

```python
recordarray2["outer", 0, "one"]
recordarray2["outer", 0, "two"]
```

used to return the two fields of the inner RecordArray, but now they return the IndexedArray that wraps around it. After thinking long and hard about it, I think this is what it should be. The test, however, should be updated to check the IndexedArray's content's identities:

```python
assert recordarray2["outer", 0, "one"].content.identities.fieldloc == [(0, "outer"), (1, "one")]
assert recordarray2["outer", 0, "two"].content.identities.fieldloc == [(0, "outer"), (1, "two")]
```

2020-06-17 19:44 UTC, jpivarski commented on tests/test_0025-record-array.py
> +    assert recordarray2[2, "outer"].identity == (0, 'outer') ### (2, "outer")
**Edit:** this was a mistake: see the next message below.

This second one is more subtle: it looks like an Identities mistake (either in the implementation or in the test, as above), but actually it's a bigger issue.

```python
>>> recordarray2[2, "outer"]
<Record at="0">
    <RecordArray>
        <Identities32 ref="0" fieldloc="[(0, 'outer')]" width="1" offset="0" length="1" at="0x561842346800"/>
        <field index="0" key="one">
            <NumpyArray format="l" shape="1" data="3" at="0x5618419af460">
                <Identities32 ref="0" fieldloc="[(0, 'outer') (0, 'one')]" width="1" offset="0" length="1" at="0x561842345180"/>
            </NumpyArray>
        </field>
        <field index="1" key="two">
            <ListArray64>
                <Identities32 ref="0" fieldloc="[(0, 'outer') (0, 'two')]" width="1" offset="0" length="1" at="0x5618423468e0"/>
                <starts><Index64 i="[3]" offset="0" length="1" at="0x561842346860"/></starts>
                <stops><Index64 i="[5]" offset="0" length="1" at="0x5618423468a0"/></stops>
                <content><NumpyArray format="d" shape="9" data="1.1 2.2 3.3 4.4 5.5 6.6 7.7 8.8 9.9" at="0x561841e60280">
                    <Identities64 ref="1" fieldloc="[(0, 'outer') (0, 'two')]" width="2" offset="0" length="9" at="0x5618423378a0"/>
                </NumpyArray></content>
            </ListArray64>
        </field>
    </RecordArray>
</Record>
>>> awkward1.to_list(recordarray2[2, "outer"])
{'one': 3, 'two': [4.4, 5.5]}
```

returns a record in the old implementation but

```python
>>> recordarray2[2, "outer"]
<RecordArray>
    <Identities32 ref="4" fieldloc="[(0, 'outer')]" width="2" offset="0" length="5" at="0x555c9f18d3d0"/>
    <field index="0" key="one">
        <NumpyArray format="l" shape="1" data="3" at="0x555c9f1879f0">
            <Identities32 ref="4" fieldloc="[(0, 'outer') (1, 'one')]" width="2" offset="4" length="1" at="0x555c9f18d3d0"/>
        </NumpyArray>
    </field>
    <field index="1" key="two">
        <ListOffsetArray64>
            <Identities32 ref="4" fieldloc="[(0, 'outer') (1, 'two')]" width="2" offset="4" length="1" at="0x555c9f18d3d0"/>
            <offsets><Index64 i="[3 5]" offset="2" length="2" at="0x555c9f1872b0"/></offsets>
            <content><NumpyArray format="d" shape="9" data="1.1 2.2 3.3 4.4 5.5 6.6 7.7 8.8 9.9" at="0x555c9f187c90">
                <Identities64 ref="5" fieldloc="[(0, 'outer') (1, 'two')]" width="3" offset="0" length="9" at="0x555c9f18d7b0"/>
            </NumpyArray></content>
        </ListOffsetArray64>
    </field>
</RecordArray>
>>> awkward1.to_list(recordarray2[2, "outer"])
[{'one': 3, 'two': [4.4, 5.5]}]
```

returns a single-item RecordArray in the new implementation. Something's wrong, and it's not just Identities (that's a symptom).

2020-06-17 19:44 UTC, jpivarski commented on tests/test_0025-record-array.py
> +    assert recordarray2[2, "outer"].identity == (0, 'outer') ### (2, "outer")
Actually, both inside and outside the PR, `recordarray2[2, "outer"]` is a single-element array of one record. I had mis-typed the test into the "inside PR" and "outside PR" terminals.

Outside this PR:

```python
>>> recordarray2[2, "outer"].form
{
    "class": "RecordArray",
    "contents": {
        "one": "int64",
        "two": {
            "class": "ListArray64",
            "starts": "i64",
            "stops": "i64",
            "content": "float64",
            "has_identities": true
        }
    },
    "has_identities": true
}
>>> awkward1.to_list(recordarray2[2, "outer"])
[{'one': 3, 'two': [4.4, 5.5]}]
>>> awkward1.type(recordarray2[2, "outer"])
{"one": int64, "two": var * float64}
>>> recordarray2[2, "outer"].identities
<Identities32 ref="1" fieldloc="[(0, 'outer')]" width="2" offset="0" length="1" at="0x55adba603900"/>
>>> recordarray2[2, "outer"].identities.fieldloc
[(0, 'outer')]
>>> numpy.asarray(recordarray2[2, "outer"].identities)
array([[2, 0]], dtype=int32)
```

Inside this PR:

```python
>>> recordarray2[2, "outer"].form
{
    "class": "RecordArray",
    "contents": {
        "one": "int64",
        "two": {
            "class": "ListOffsetArray64",
            "offsets": "i64",
            "content": "float64",
            "has_identities": true
        }
    },
    "has_identities": true
}
>>> awkward1.to_list(recordarray2[2, "outer"])
[{'one': 3, 'two': [4.4, 5.5]}]
>>> awkward1.type(recordarray2[2, "outer"])
{"one": int64, "two": var * float64}
>>> recordarray2[2, "outer"].identities
<Identities32 ref="1" fieldloc="[(0, 'outer')]" width="2" offset="0" length="5" at="0x5619d0d1ac50"/>
>>> recordarray2[2, "outer"].identities.fieldloc
[(0, 'outer')]
>>> numpy.asarray(recordarray2[2, "outer"].identities)
array([[0, 0],
       [1, 0],
       [2, 0],
       [3, 0],
       [4, 0]], dtype=int32)
```

So the ListArray in one case is a ListOffsetArray in the other case—which might be benign in itself—but the Identities are clearly wrong in the PR. An array of length N should have length N Identities, but this array of length 1 has Identities of length 5. Something didn't get dereferenced.

The ListArray vs. ListOffsetArray is probably a clue. Again, having a different form in the two cases might be okay—slicing a RecordArray is different from slicing an IndexedArray, and the most optimal list type is chosen for each case. (I haven't thought deeply into _this_ case, though.) However, the fact that they're different could reveal what's different about the Identities.

At the moment, it only looks like the Identities are wrong, but they might be an indication of a deeper bug.

2020-06-18 12:40 UTC, ianna commented on include/awkward/Content.h
> +      carry(const Index64& carry, bool copy = false) const = 0;
I've changed it to `must_be_eager` - it's easier to keep track of which carry must be eager :-)
I can swap it to `allow_lazy` later when everything works.

2020-06-18 12:40 UTC, ianna commented on include/awkward/array/RawArray.h
> +        return carry(nextcarry, true);
done

2020-06-18 12:40 UTC, ianna commented on include/awkward/array/RawArray.h
> +      return carry(flathead, true);
done

2020-06-19 08:04 UTC, ianna commented
@jpivarski - FYI, to have a clean build I just picked up a master and tried to build it on my Mac. There is a failure in the test:
```python
==================================================================================== FAILURES ====================================================================================
____________________________________________________________________________ test_inhibit_matplotlib _____________________________________________________________________________

    def test_inhibit_matplotlib():
        array = awkward1.Array([1.1, 2.2, 3.3, 4.4, 5.5], check_valid=True)
        plt.hist(array)
        plt.plot(array)
>       plt.plot(array, array)

tests/test_0089-numpy-functions.py:175: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/matplotlib/pyplot.py:2987: in plot
    ret = ax.plot(*args, **kwargs)
/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/matplotlib/axes.py:4137: in plot
    for line in self._get_lines(*args, **kwargs):
/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/matplotlib/axes.py:317: in _grab_next_args
    for seg in self._plot_args(remaining, kwargs):
/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/matplotlib/axes.py:276: in _plot_args
    linestyle, marker, color = _process_plot_format(tup[-1])
/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/matplotlib/axes.py:80: in _process_plot_format
    color = mcolors.colorConverter.to_rgb(fmt)
/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/matplotlib/colors.py:291: in to_rgb
    argl = arg.lower()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <Array [1.1, 2.2, 3.3, 4.4, 5.5] type='5 * float64'>, where = 'lower'

    def __getattr__(self, where):
        """
        Whenever possible, fields can be accessed as attributes.
    
        For example, the fields of an `array` like
    
            ak.Array([[{"x": 1.1, "y": [1]}, {"x": 2.2, "y": [2, 2]}, {"x": 3.3, "y": [3, 3, 3]}],
                      [],
                      [{"x": 4.4, "y": [4, 4, 4, 4]}, {"x": 5.5, "y": [5, 5, 5, 5, 5]}]])
    
        can be accessed as
    
            >>> array.x
            <Array [[1.1, 2.2, 3.3], [], [4.4, 5.5]] type='3 * var * float64'>
            >>> array.y
            <Array [[[1], [2, 2], ... [5, 5, 5, 5, 5]]] type='3 * var * var * int64'>
    
        which are equivalent to `array["x"]` and `array["y"]`. (See
        <<projection>>.)
    
        Fields can't be accessed as attributes when
    
           * #ak.Array methods or properties take precedence,
           * a domain-specific behavior has methods or properties that take
             precedence, or
           * the field name is not a valid Python identifier or is a Python
             keyword.
    
        Note that while fields can be accessed as attributes, they cannot be
        *assigned* as attributes: the following doesn't work.
    
            array.z = new_field
    
        Always use
    
            array["z"] = new_field
    
        to add a field.
        """
        if where in dir(type(self)):
            return super(Array, self).__getattribute__(where)
        else:
            if where in self._layout.keys():
                try:
                    return self[where]
                except Exception as err:
                    raise AttributeError(
                        "while trying to get field {0}, an exception "
                        "occurred:\n{1}: {2}".format(repr(where), type(err), str(err))
                    )
            else:
>               raise AttributeError("no field named {0}".format(repr(where)))
E               AttributeError: no field named 'lower'

awkward1/highlevel.py:958: AttributeError
============================================================================ short test summary info =============================================================================
SKIPPED [1] /Users/yana/Projects/PR204-clean/awkward-1.0/tests/test_0135-awkward0-awkward1-converter.py:13: could not import 'awkward': No module named awkward
SKIPPED [1] /Users/yana/Projects/PR204-clean/awkward-1.0/tests/test_0031-pickle-types.py:16: pybind11 pickle only works in Python 3
SKIPPED [1] /Users/yana/Projects/PR204-clean/awkward-1.0/tests/test_0224-arrow-to-awkward.py:13: could not import 'pyarrow': No module named pyarrow
SKIPPED [1] /Users/yana/Projects/PR204-clean/awkward-1.0/tests/test_0120-autograd-support.py:13: could not import 'autograd': No module named autograd
SKIPPED [1] /Users/yana/Projects/PR204-clean/awkward-1.0/tests/test_0118-numba-cpointers.py:14: could not import 'numba': No module named numba
SKIPPED [1] /Users/yana/Projects/PR204-clean/awkward-1.0/tests/test_0290-bug-fixes-for-hats.py:13: could not import 'numba': No module named numba
SKIPPED [1] /Users/yana/Projects/PR204-clean/awkward-1.0/tests/test_0119-numexpr-and-broadcast-arrays.py:13: could not import 'numexpr': No module named numexpr
SKIPPED [1] /Users/yana/Projects/PR204-clean/awkward-1.0/tests/test_0127b-tomask-operation-numba.py:13: could not import 'numba': No module named numba
SKIPPED [1] /Users/yana/Projects/PR204-clean/awkward-1.0/tests/test_0090-as-pandas-extension.py:16: could not import 'pandas': No module named pandas
SKIPPED [1] /Users/yana/Projects/PR204-clean/awkward-1.0/tests/test_0080-flatpandas-multiindex-rows-and-columns.py:15: could not import 'pandas': No module named pandas
SKIPPED [1] /Users/yana/Projects/PR204-clean/awkward-1.0/tests/test_0057b-virtual-array-numba.py:14: could not import 'numba': No module named numba
SKIPPED [1] /Users/yana/Projects/PR204-clean/awkward-1.0/tests/test_0124-strings-in-numba.py:13: could not import 'numba': No module named numba
SKIPPED [1] /Users/yana/Projects/PR204-clean/awkward-1.0/tests/test_0056b-partitioned-array-numba.py:13: could not import 'numba': No module named numba
=============================================================== 1 failed, 358 passed, 13 skipped in 12.03 seconds ================================================================
Traceback (most recent call last):
  File "localbuild.py", line 135, in <module>
    check_call(["python", "-m", "pytest", "-vv", "-rs", args.pytest], env=env)
  File "localbuild.py", line 57, in check_call
    return subprocess.check_call(args, env=env)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['python', '-m', 'pytest', '-vv', '-rs', 'tests']' returned non-zero exit status 1
yana@iannas-macbook-pro-2 awkward-1.0 % 

```

2020-06-19 08:34 UTC, ianna commented on tests/test_0025-record-array.py
> +    assert a[2, "outer"].identity == (0, 'outer')
@jpivarski - this test passes in a clean build without this PR

2020-06-19 11:40 UTC, jpivarski commented
> FYI, to have a clean build I just picked up a master and tried to build it on my Mac. There is a failure in the test

This is an error _in_ Matplotlib, something unrelated to the thing we're testing (colors?), and is probably due to a bad Matplotlib installation. It's an optional test—if you don't have Matplotlib installed, it will be skipped. (I do have Matplotlib installed, and the test runs fine; CI does not and skips it.)

If you don't need Matplotlib, you can uninstall your copy and the test will be skipped. Otherwise, you probably want to fix your installation, anyway. If you do have Matplotlib and it works in other contexts, then I don't know what's going on.

I usually install these things with Conda (exclusively—I switched over about a year ago with a new computer). It manages binary versions of all your packages so that you always have a compatible set (which is why it has to be exclusive—it was hard to switch over from apt-get without starting fresh). The downside of this is that installing one little package sometimes means upgrading 20 others and downgrading 5, but at least they all work together.

2020-06-19 12:36 UTC, ianna commented
> > FYI, to have a clean build I just picked up a master and tried to build it on my Mac. There is a failure in the test
> 
> This is an error _in_ Matplotlib, something unrelated to the thing we're testing (colors?), and is probably due to a bad Matplotlib installation. It's an optional test—if you don't have Matplotlib installed, it will be skipped. (I do have Matplotlib installed, and the test runs fine; CI does not and skips it.)
> 
> If you don't need Matplotlib, you can uninstall your copy and the test will be skipped. Otherwise, you probably want to fix your installation, anyway. If you do have Matplotlib and it works in other contexts, then I don't know what's going on.
> 
> I usually install these things with Conda (exclusively—I switched over about a year ago with a new computer). It manages binary versions of all your packages so that you always have a compatible set (which is why it has to be exclusive—it was hard to switch over from apt-get without starting fresh). The downside of this is that installing one little package sometimes means upgrading 20 others and downgrading 5, but at least they all work together.

Thanks, Jim! Yes, I've done that. It's just I haven't seen this kind of failure before and thought I'd let you know.

2020-06-19 12:41 UTC, jpivarski commented
> It's just I haven't seen this kind of failure before and thought I'd let you know.

Thanks!

2020-06-22 10:48 UTC, ianna commented on tests/test_0025-record-array.py
> +    assert recordarray2[2, "outer"].identity == (0, 'outer') ### (2, "outer")
@jpivarski - I traced it to a field slicing, so currently an eager carry `RecordArray` is a work-around it.

2020-06-22 15:48 UTC, ianna commented
@jpivarski - Unrelated to this PR - it looks like there is an initialisation problem somewhere. My guess, it's an "offset" value causing an out of range access. It happens very rarely and the tests would pass just fine on subsequent runs. 

Here is where I've seen it locally:
```python
       array4 = array3.rpad(3, 1)
        assert awkward1.to_list(array4) == [
            [2.2, 1.1, 3.3],
            [None, None, None],
            [4.4, 5.5, None],
            [5.5, None, None],
            [-4.4, -5.5, -6.6]]
    
        array5 = array4.sort(0, True, False)
>       assert awkward1.to_list(array5.sort(0, True, False)) == [
            [-4.4, -5.5, -6.6],
            [2.2, 1.1, 3.3],
            [4.4, 5.5, None],
            [5.5, None, None],
            [None, None, None]]

tests/test_0074-argsort-and-sort.py:177: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
awkward1/operations/convert.py:403: in to_list
    return [to_list(x) for x in array]
awkward1/operations/convert.py:403: in <listcomp>
    return [to_list(x) for x in array]
awkward1/operations/convert.py:403: in to_list
    return [to_list(x) for x in array]
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

.0 = <Iterator at="3">
    <IndexedOptionArray64>
        <index><Index64 i="[2 6 9]" offset="6" length="3" at="0x7ff894544..." data="-4.4 2.2 4.4 5.5 -5.5 1.1 5.5 -6.6 3.3" at="0x7ff894545040"/></content>
    </IndexedOptionArray64>
</Iterator>

>   return [to_list(x) for x in array]
E   ValueError: in IndexedOptionArray64 attempting to get 2, index[i] >= len(content)

awkward1/operations/convert.py:403: ValueError

```
and in the build of this PR on MacOS/Python 2.7:
```python
>       assert awkward1.to_list(array.argsort(0, True, False)) == [
            [    3,    1,    2 ],
            [    0,    0,    0 ],
            [    1, None,    1 ],
            [    2, None, None ],
            [ None, None, None ]]

tests/test_0074-argsort-and-sort.py:122: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
/Users/runner/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/site-packages/awkward1/operations/convert.py:403: in to_list
    return [to_list(x) for x in array]
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

array = <IndexedOptionArray64>
    <index><Index64 i="[3 -1 9]" offset="9" length="3" ...ata="3 0 1 2 1 0 2 0 1" at="0x7fa0ecf3f2f0"/></content>
</IndexedOptionArray64>

>           return [to_list(x) for x in array]
E           ValueError: in IndexedOptionArray64 attempting to get 2, index[i] >= len(content)

```

2020-06-22 16:06 UTC, jpivarski commented
> Unrelated to this PR - it looks like there is an initialisation problem somewhere. My guess, it's an "offset" value causing an out of range access. It happens very rarely and the tests would pass just fine on subsequent runs.

Rare bugs are the worst. If it is related to an offset, you may be able to coerce it to always happen by doing a test on a slice: `somearray[2:]` introduces an offset `2` into one of the Indexes. You just have to be careful then that you don't do another operation that invokes a copy, effectively eliminating the offset of `2` (new copies have offsets of `0`). Note that slices like `somearray[:, 2:]` do a copy, since the first dimension might be jagged.

2020-06-26 07:46 UTC, ianna commented
@jpivarski - FYI - picked up the master branch this morning:
```
yana@iannas-macbook-pro-2 Tests % git clone --recursive https://github.com/scikit-hep/awkward-1.0.git
Cloning into 'awkward-1.0'...
remote: Enumerating objects: 864, done.
remote: Counting objects: 100% (864/864), done.
remote: Compressing objects: 100% (455/455), done.
remote: Total 8483 (delta 628), reused 569 (delta 379), pack-reused 7619
Receiving objects: 100% (8483/8483), 6.69 MiB | 5.00 MiB/s, done.
Resolving deltas: 100% (5960/5960), done.
Submodule 'pybind11' (https://github.com/pybind/pybind11.git) registered for path 'pybind11'
Submodule 'rapidjson' (https://github.com/Tencent/rapidjson.git) registered for path 'rapidjson'
Cloning into '/Users/yana/Projects/Tests/awkward-1.0/pybind11'...
remote: Enumerating objects: 8, done.        
remote: Counting objects: 100% (8/8), done.        
remote: Compressing objects: 100% (6/6), done.        
remote: Total 11566 (delta 1), reused 6 (delta 1), pack-reused 11558        
Receiving objects: 100% (11566/11566), 4.32 MiB | 3.47 MiB/s, done.
Resolving deltas: 100% (7812/7812), done.
Cloning into '/Users/yana/Projects/Tests/awkward-1.0/rapidjson'...
remote: Enumerating objects: 171, done.        
remote: Counting objects: 100% (171/171), done.        
remote: Compressing objects: 100% (134/134), done.        
remote: Total 22913 (delta 51), reused 56 (delta 35), pack-reused 22742        
Receiving objects: 100% (22913/22913), 27.27 MiB | 14.82 MiB/s, done.
Resolving deltas: 100% (17367/17367), done.
Submodule path 'pybind11': checked out '80d452484c5409444b0ec19383faa84bb7a4d351'
Submodule 'tools/clang' (https://github.com/wjakob/clang-cindex-python3) registered for path 'pybind11/tools/clang'
Cloning into '/Users/yana/Projects/Tests/awkward-1.0/pybind11/tools/clang'...
remote: Enumerating objects: 8, done.        
remote: Counting objects: 100% (8/8), done.        
remote: Compressing objects: 100% (8/8), done.        
remote: Total 361 (delta 2), reused 2 (delta 0), pack-reused 353        
Receiving objects: 100% (361/361), 147.50 KiB | 920.00 KiB/s, done.
Resolving deltas: 100% (151/151), done.
Submodule path 'pybind11/tools/clang': checked out '6a00cbc4a9b8e68b71caf7f774b3f9c753ae84d5'
Submodule path 'rapidjson': checked out 'f54b0e47a08782a6131cc3d60f94d038fa6e0a51'
Submodule 'thirdparty/gtest' (https://github.com/google/googletest.git) registered for path 'rapidjson/thirdparty/gtest'
Cloning into '/Users/yana/Projects/Tests/awkward-1.0/rapidjson/thirdparty/gtest'...
remote: Enumerating objects: 19, done.        
remote: Counting objects: 100% (19/19), done.        
remote: Compressing objects: 100% (13/13), done.        
remote: Total 20613 (delta 4), reused 10 (delta 4), pack-reused 20594        
Receiving objects: 100% (20613/20613), 7.68 MiB | 2.26 MiB/s, done.
Resolving deltas: 100% (15237/15237), done.
Submodule path 'rapidjson/thirdparty/gtest': checked out '0a439623f75c029912728d80cb7f1b8b48739ca4'
```
```
yana@iannas-macbook-pro-2 Tests % cd awkward-1.0 
yana@iannas-macbook-pro-2 awkward-1.0 % python localbuild.py --pytest tests
pip install -r requirements.txt -r requirements-test.txt
Requirement already satisfied: numpy>=1.13.1 in /Users/yana/.pyenv/versions/3.8.1/lib/python3.8/site-packages (from -r requirements.txt (line 1)) (1.18.1)
Requirement already satisfied: pytest>=3.9 in /Users/yana/.pyenv/versions/3.8.1/lib/python3.8/site-packages (from -r requirements-test.txt (line 1)) (5.3.5)
Requirement already satisfied: pluggy<1.0,>=0.12 in /Users/yana/.pyenv/versions/3.8.1/lib/python3.8/site-packages (from pytest>=3.9->-r requirements-test.txt (line 1)) (0.13.1)
Requirement already satisfied: wcwidth in /Users/yana/.pyenv/versions/3.8.1/lib/python3.8/site-packages (from pytest>=3.9->-r requirements-test.txt (line 1)) (0.1.8)
Requirement already satisfied: py>=1.5.0 in /Users/yana/.pyenv/versions/3.8.1/lib/python3.8/site-packages (from pytest>=3.9->-r requirements-test.txt (line 1)) (1.8.1)
Requirement already satisfied: packaging in /Users/yana/.pyenv/versions/3.8.1/lib/python3.8/site-packages (from pytest>=3.9->-r requirements-test.txt (line 1)) (20.3)
Requirement already satisfied: attrs>=17.4.0 in /Users/yana/.pyenv/versions/3.8.1/lib/python3.8/site-packages (from pytest>=3.9->-r requirements-test.txt (line 1)) (19.3.0)
Requirement already satisfied: more-itertools>=4.0.0 in /Users/yana/.pyenv/versions/3.8.1/lib/python3.8/site-packages (from pytest>=3.9->-r requirements-test.txt (line 1)) (8.2.0)
Requirement already satisfied: pyparsing>=2.0.2 in /Users/yana/.pyenv/versions/3.8.1/lib/python3.8/site-packages (from packaging->pytest>=3.9->-r requirements-test.txt (line 1)) (2.4.6)
Requirement already satisfied: six in /Users/yana/.pyenv/versions/3.8.1/lib/python3.8/site-packages (from packaging->pytest>=3.9->-r requirements-test.txt (line 1)) (1.14.0)
cmake -S . -Blocalbuild -DCMAKE_BUILD_TYPE=Debug -DPYTHON_EXECUTABLE=/Users/yana/.pyenv/versions/3.8.1/bin/python -DPYBUILD=ON
-- The CXX compiler identification is AppleClang 11.0.3.11030032
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- CMake version 3.16.4
-- Debug
-- Found PythonInterp: /Users/yana/.pyenv/versions/3.8.1/bin/python (found version "3.8.1") 
-- Found PythonLibs: /Users/yana/.pyenv/versions/3.8.1/lib/libpython3.8.a
-- pybind11 v2.4.3
-- Performing Test HAS_FLTO
-- Performing Test HAS_FLTO - Success
-- LTO enabled
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/yana/Projects/Tests/awkward-1.0/localbuild
cmake --build localbuild -- -j12
Scanning dependencies of target awkward-cpu-kernels-objects
Scanning dependencies of target awkward-objects
[  3%] Building CXX object CMakeFiles/awkward-cpu-kernels-objects.dir/src/cpu-kernels/sorting.cpp.o
[  3%] Building CXX object CMakeFiles/awkward-cpu-kernels-objects.dir/src/cpu-kernels/identities.cpp.o
[  3%] Building CXX object CMakeFiles/awkward-cpu-kernels-objects.dir/src/cpu-kernels/reducers.cpp.o
[  6%] Building CXX object CMakeFiles/awkward-cpu-kernels-objects.dir/src/cpu-kernels/getitem.cpp.o
[  6%] Building CXX object CMakeFiles/awkward-cpu-kernels-objects.dir/src/cpu-kernels/operations.cpp.o
[  8%] Building CXX object CMakeFiles/awkward-objects.dir/src/libawkward/Content.cpp.o
[ 10%] Building CXX object CMakeFiles/awkward-objects.dir/src/libawkward/Identities.cpp.o
[ 10%] Building CXX object CMakeFiles/awkward-objects.dir/src/libawkward/Index.cpp.o
[ 11%] Building CXX object CMakeFiles/awkward-objects.dir/src/libawkward/Iterator.cpp.o
[ 13%] Building CXX object CMakeFiles/awkward-objects.dir/src/libawkward/Reducer.cpp.o
[ 13%] Building CXX object CMakeFiles/awkward-objects.dir/src/libawkward/Slice.cpp.o
[ 15%] Building CXX object CMakeFiles/awkward-objects.dir/src/libawkward/array/BitMaskedArray.cpp.o
[ 16%] Building CXX object CMakeFiles/awkward-objects.dir/src/libawkward/array/ByteMaskedArray.cpp.o
[ 17%] Building CXX object CMakeFiles/awkward-objects.dir/src/libawkward/array/EmptyArray.cpp.o
[ 18%] Building CXX object CMakeFiles/awkward-objects.dir/src/libawkward/array/IndexedArray.cpp.o
[ 20%] Building CXX object CMakeFiles/awkward-objects.dir/src/libawkward/array/ListArray.cpp.o
[ 21%] Building CXX object CMakeFiles/awkward-objects.dir/src/libawkward/array/ListOffsetArray.cpp.o
[ 22%] Building CXX object CMakeFiles/awkward-objects.dir/src/libawkward/array/None.cpp.o
[ 24%] Building CXX object CMakeFiles/awkward-objects.dir/src/libawkward/array/NumpyArray.cpp.o
[ 25%] Building CXX object CMakeFiles/awkward-objects.dir/src/libawkward/array/Record.cpp.o
[ 26%] Building CXX object CMakeFiles/awkward-objects.dir/s [...]

2020-06-26 09:00 UTC, ianna commented
@jpivarski - I'm running into some problems (see at the end of the log). Perhaps, you could have a look and suggest what should I do. I'm using the master branch and following the https://github.com/jpivarski/2020-04-08-eic-jlab/blob/master/2020-04-08-eic-jlab-EVALUATED.ipynb workbook.
```python
In [61]: print(awkward1.__version__)                                                                                                         
0.2.25

```
Most of the instructions work fine:
```python
In [3]: import uproot                                                                                                                        

In [4]: file = uproot.open("../../PR204/awkward-1.0/open_charm_18x275_10k.root")                                                             

In [5]: tree = file["events/tree"]                                                                                                           

In [6]: evt_id, evt_prt_count = tree.arrays(["evt_id", "evt_prt_count"], outputtype=tuple)                                                   

In [7]: tree.array("evt_id", entrystart=500, entrystop=600)                                                                                  
Out[7]: 
array([500, 501, 502, 503, 504, 505, 506, 507, 508, 509, 510, 511, 512,
       513, 514, 515, 516, 517, 518, 519, 520, 521, 522, 523, 524, 525,
       526, 527, 528, 529, 530, 531, 532, 533, 534, 535, 536, 537, 538,
       539, 540, 541, 542, 543, 544, 545, 546, 547, 548, 549, 550, 551,
       552, 553, 554, 555, 556, 557, 558, 559, 560, 561, 562, 563, 564,
       565, 566, 567, 568, 569, 570, 571, 572, 573, 574, 575, 576, 577,
       578, 579, 580, 581, 582, 583, 584, 585, 586, 587, 588, 589, 590,
       591, 592, 593, 594, 595, 596, 597, 598, 599], dtype=uint64)

In [8]: # Make a cache with an acceptable limit. 
   ...: gigabyte_cache = uproot.ArrayCache("1 GB") 
   ...:  
   ...: # Read the array from disk: 
   ...: tree.array("evt_id", cache=gigabyte_cache) 
   ...:  
   ...: # Get the array from the cache: 
   ...: tree.array("evt_id", cache=gigabyte_cache)                                                                                           
Out[8]: array([   0,    1,    2, ..., 9997, 9998, 9999], dtype=uint64)

In [9]: %%timeit 
   ...:  
   ...: tree.arrays("*") 
   ...:  
   ...:                                                                                                                                      
534 ms ± 6.81 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

In [10]: %%timeit 
    ...:  
    ...: tree.arrays("*", cache=gigabyte_cache) 
    ...:  
    ...:                                                                                                                                     
2.53 ms ± 46.4 µs per loop (mean ± std. dev. of 7 runs, 1 loop each)

In [11]: len(gigabyte_cache)                                                                                                                 
Out[11]: 52

In [12]: gigabyte_cache.clear()                                                                                                              

In [13]: len(gigabyte_cache)                                                                                                                 
Out[13]: 0

In [14]: for arrays in tree.iterate("evt_*", entrysteps=1000): 
    ...:     print({name: len(array) for name, array in arrays.items()}) 
    ...:                                                                                                                                     
{b'evt_id': 1000, b'evt_true_q2': 1000, b'evt_true_x': 1000, b'evt_true_y': 1000, b'evt_true_w2': 1000, b'evt_true_nu': 1000, b'evt_has_dis_info': 1000, b'evt_prt_count': 1000, b'evt_weight': 1000}
{b'evt_id': 1000, b'evt_true_q2': 1000, b'evt_true_x': 1000, b'evt_true_y': 1000, b'evt_true_w2': 1000, b'evt_true_nu': 1000, b'evt_has_dis_info': 1000, b'evt_prt_count': 1000, b'evt_weight': 1000}
{b'evt_id': 1000, b'evt_true_q2': 1000, b'evt_true_x': 1000, b'evt_true_y': 1000, b'evt_true_w2': 1000, b'evt_true_nu': 1000, b'evt_has_dis_info': 1000, b'evt_prt_count': 1000, b'evt_weight': 1000}
{b'evt_id': 1000, b'evt_true_q2': 1000, b'evt_true_x': 1000, b'evt_true_y': 1000, b'evt_true_w2': 1000, b'evt_true_nu': 1000, b'evt_has_dis_info': 1000, b'evt_prt_count': 1000, b'evt_weight': 1000}
{b'evt_id': 1000, b'evt_true_q2': 1000, b'evt_true_x': 1000, b'evt_true_y': 1000, b'evt_true_w2': 1000, b'evt_true_nu': 1000, b'evt_has_dis_info': 1000, b'evt_prt_count': 1000, b'evt_weight': 1000}
{b'evt_id': 1000, b'evt_true_q2': 1000, b'evt_true_x': 1000, b'evt_true_y': 1000, b'evt_true_w2': 1000, b'evt_true_nu': 1000, b'evt_has_dis_info': 1000, b'evt_prt_count': 1000, b'evt_weight': 1000}
{b'evt_id': 1000, b'evt_true_q2': 1000, b'evt_true_x': 1000, b'evt_true_y': 1000, b'evt_true_w2': 1000, b'evt_true_nu': 1000, b'evt_has_dis_info': 1000, b'evt_prt_count': 1000, b'evt_weight': 1000}
{b'evt_id': 1000, b'evt_true_q2': 1000, b'evt_true_x': 1000, b'evt_true_y': 1000, b'evt_true_w2': 1000, b'evt_true_nu': 1000, b'evt_has_dis_info': 1000, b'evt_prt_count': 1000, b'evt_weight': 1000}
{b'evt_id': 1000, b'evt_true_q2': 1000, b'evt_true_x': 1000, b'evt_true_y': 1000, b'evt_true_w2': 1000, b'evt_true_nu': 1000, b'evt_has_dis_info': 1000, b'evt_prt_count': 1000, b'evt_weight': 1000}
{b'evt_id': 1000, b'evt_true_q2': 1000, b'evt_true_x': 1000, b'evt_true_y': 1000, b'evt_true_w2': 1000, b'evt_true_nu': 1000, b'evt_has_dis_info': 1000, b'evt_prt_count': 1000, b'evt_weight': 1000}

In [15]: for arrays in tree.iterate("evt_*", entrysteps="100 kB"): 
    ...:     print({name: len(array) for name, array in arrays.items()}) 
    ...:                                                                                                                                     
{b'evt_id': 1576, b'evt_true_q2': 1576, b'evt_true_x': 1576, b'evt_true_y': 1576, b'evt_true_w2': 1576, b'evt_true_nu': 1576, b'evt_has_dis_info': 1576, b'evt_prt_count': 1576, b'evt_weight': 1576}
{b'evt_id': 1576, b'evt_true_q2': 1576, b'evt_true_x': 1576, b'evt_true_y': 1576, b'evt_true_w2': 1576, b'evt_true_nu': 1576, b'evt_has_dis_info': 1576, b'evt_prt_count': 1576, b'evt_weight': 1576}
{b'evt_id': 1576, b'evt_true_q2': 1576, b'evt_true_x': 1576, b'evt_true_y': 1576, b'evt_true_w2': 1576, b'evt_true_nu': 1576, b'evt_has_dis_info': 1576, b'evt_prt_count': 1576, b'evt_weight': 1576}
{b'evt_id': 1576, b'evt_true_q2': 1576, b'evt_true_x': 1576, b'evt_true_y': 1576, b'evt_true_w2': 1576, b'evt_true_nu': 1576, b'evt_has_dis_info': 1576, b'evt_prt_count': 1576, b'evt_weight': 1576}
{b'evt_id': 1576, b'evt_true_q2': 1576, b'evt_true_x': 1576, b'evt_true_y': 1576, b'evt_true_w2': 1576, b'evt_true_nu': 1576, b'evt_has_dis_info': 1576, b'evt_prt_count': 1576, b'evt_weight': 1576}
{b'evt_id': 1576, b'evt_true_q2': 1576, b'evt_true_x': 1576, b'evt_true_y': 1576, b'evt_true_w2': 1576, b'evt_true_nu': 1576, b'evt_has_dis_info': 1576, b'evt_prt_count': 1576, b'evt_weight': 1576}
{b'evt_id': 544, b'evt_true_q2': 544, b'evt_true_x': 544, b'evt_true_y': 544, b'evt_true_w2': 544, b'evt_true_nu': 544, b'evt_has_dis_info': 544, b'evt_prt_count': 544, b'evt_weight': 544}

In [16]: for arrays in tree.iterate("evt_id", entrysteps="100 kB"): 
    ...:     print({name: len(array) for name, array in arrays.items()}) 
    ...:                                                                                                                                     
{b'evt_id': 10000}

```

```python
In [29]: import awkward1 as ak                                                                                                               

In [30]: ak.from_awkward0(tree.array("pdg"))                                                                                                 
Out[30]: <Array [[11, 211, -211, -321, ... 130, 22, 22]] type='10000 * var * int64'>

In [31]: arrays = {name: ak.from_awkward0(array) for name, array in tree.arrays(namedecode="utf-8") [...]

2020-06-26 10:38 UTC, jpivarski commented
For the failed unit tests, update Numba. The new minimum version of Numba is 0.50, because I've been in communication with them about fixing their "entry points" (which we rely on), and they fixed it on Numba 0.50. If you have any pip-installed versions of Awkward, try uninstalling them (and maybe even installing and uninstalling a new version of Awkward from PyPI using pip, to ensure that the bad entry points are removed: entry points are a package-level thing). Specifically, the tests are failing because we now rely on entry points to declare Awkward-Numba types when Numba is loaded, not when Awkward is loaded, and with the wrong combination, those types never get defined and the tests fail.

2020-06-26 10:43 UTC, jpivarski commented
For `depthlimit` disappearing—actually, it's just the spelling that's changed: `depthlimit` → `depth_limit`. Before the first public demo, I poked the community about names, and there was a strong, widespread opinion that words like this should be separated with underscores. I've found and changed most public-facing ones (it matters less what words we use internally), but there are a few left. There's an open issue to fix `keep_something` (I can't remember the second word). Word pairs that we have for consistency with NumPy are an exception: NumPy had a `keepdims`, for insurance, so we use exactly the same spelling they do.

2020-06-26 10:45 UTC, ianna commented
> For `depthlimit` disappearing—actually, it's just the spelling that's changed: `depthlimit` → `depth_limit`. Before the first public demo, I poked the community about names, and there was a strong, widespread opinion that words like this should be separated with underscores. I've found and changed most public-facing ones (it matters less what words we use internally), but there are a few left. There's an open issue to fix `keep_something` (I can't remember the second word). Word pairs that we have for consistency with NumPy are an exception: NumPy had a `keepdims`, for insurance, so we use exactly the same spelling they do.

Thanks @jpivarski!

2020-06-26 10:48 UTC, ianna commented
> For the failed unit tests, update Numba. The new minimum version of Numba is 0.50, because I've been in communication with them about fixing their "entry points" (which we rely on), and they fixed it on Numba 0.50. If you have any pip-installed versions of Awkward, try uninstalling them (and maybe even installing and uninstalling a new version of Awkward from PyPI using pip, to ensure that the bad entry points are removed: entry points are a package-level thing). Specifically, the tests are failing because we now rely on entry points to declare Awkward-Numba types when Numba is loaded, not when Awkward is loaded, and with the wrong combination, those types never get defined and the tests fail.

Has anyone looking into updating the build to add a warning about it?

2020-06-26 11:04 UTC, jpivarski commented
> Has anyone looking into updating the build to add a warning about it?

Now that I think about it, you should have been hit by this:

https://github.com/scikit-hep/awkward-1.0/blob/62d79bc3b8b2f38c472856e7b884f36b1eb95076/src/awkward1/_connect/_numba/__init__.py#L29-L36

which would have given you a bunch of messages like

```
awkward1 can only work with numba 0.50 or later (you have version 0.49)
```

I wonder why that didn't happen—you do have the latest Python code because you merged with master.

Beyond that, I expect that most of the users will be starting in the future (Awkward 0 has a big userbase; Awkward 1 does not, yet), and for them, the minimum Numba will always be 0.50.

2020-06-26 11:07 UTC, ianna commented
> > Has anyone looking into updating the build to add a warning about it?
> 
> Now that I think about it, you should have been hit by this:
> 
> https://github.com/scikit-hep/awkward-1.0/blob/62d79bc3b8b2f38c472856e7b884f36b1eb95076/src/awkward1/_connect/_numba/__init__.py#L29-L36
> 
> which would have given you a bunch of messages like
> 
> ```
> awkward1 can only work with numba 0.50 or later (you have version 0.49)
> ```
> 
> I wonder why that didn't happen—you do have the latest Python code because you merged with master.
> 
> Beyond that, I expect that most of the users will be starting in the future (Awkward 0 has a big userbase; Awkward 1 does not, yet), and for them, the minimum Numba will always be 0.50.

Hmm... I'll look into it.

2020-06-26 13:45 UTC, ianna commented
@jpivarski - please, see the benchmark results on MacOS 10.15.5 (19F101) 2.6 GHz 6-Core Intel Core i7

Awkward array version 0.2.25:
```python
In [72]: %%timeit -n1000 -r1 
    ...: pairs = ak.cartesian([events.pions, events.protons], with_name="pair") 
    ...:  
    ...:                                                                                                                                     
67.4 ms ± 0 ns per loop (mean ± std. dev. of 1 run, 1000 loops each)

In [80]: %%timeit -n100 -r1 
    ...: pairs = ak.combinations(events.pions, 2, with_name="pair") 
    ...:  
    ...:                                                                                                                                     
356 ms ± 0 ns per loop (mean ± std. dev. of 1 run, 100 loops each)

In [83]: %%timeit 
    ...: pizero_candidates = ak.combinations(events.prt[events.prt.pdg == Particle.from_string("gamma").pdgid], 2, with_name="pair") 
    ...:  
    ...:                                                                                                                                     
830 ms ± 14.7 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

In [85]: evts = events.prt[events.prt.pdg == Particle.from_string("gamma").pdgid]                                                            

In [86]: %%timeit 
    ...: pizero_candidates = ak.combinations(evts, 2, with_name="pair") 
    ...:  
    ...:                                                                                                                                     
551 ms ± 2 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```
Awkward array version 0.2.25 with this PR:
```python
In [38]: %%timeit -n1000 -r1  
    ...: pairs = ak.cartesian([events.pions, events.protons], with_name="pair") 
    ...:  
    ...:                                                                                                                                     
24.5 ms ± 0 ns per loop (mean ± std. dev. of 1 run, 1000 loops each)

In [43]: %%timeit -n100 -r1 
    ...: pairs = ak.combinations(events.pions, 2, with_name="pair") 
    ...:  
    ...:                                                                                                                                     
44.2 ms ± 0 ns per loop (mean ± std. dev. of 1 run, 100 loops each)

In [46]: %%timeit 
    ...: pizero_candidates = ak.combinations(events.prt[events.prt.pdg == Particle.from_string("gamma").pdgid], 2, with_name="pair") 
    ...:  
    ...:                                                                                                                                     
655 ms ± 104 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

In [47]: evts = events.prt[events.prt.pdg == Particle.from_string("gamma").pdgid]                                                            

In [48]: %%timeit  
    ...: pizero_candidates = ak.combinations(evts, 2, with_name="pair") 
    ...:  
    ...:                                                                                                                                     
50.6 ms ± 7.86 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
```

2020-06-26 14:15 UTC, jpivarski commented
> @jpivarski - please, see the benchmark results on MacOS 10.15.5 (19F101) 2.6 GHz 6-Core Intel Core i7

These look great!

The PR accomplished its goal of speeding up operations on big records:

   * Cartesian product with big records (pions and protons): 2.7×
   * Combinations with big records (pions): 8×
   * Combinations with big records (photons): 11× (with the much slower photon selection factored out)

The reason it was a fix to `RecordArray::carry`, rather than `ak.cartesian` and `ak.combinations`, was so that performance on non-records wouldn't be worsened. But since these weren't changed, they can't be any faster or slower than they were.

I looked into the one failing test, but I couldn't see what was going on there. I just [triggered a test on master](https://dev.azure.com/jpivarski/Scikit-HEP/_build/results?buildId=2247&view=results) to see if it's some new bug that's crept in due to dependencies changing under us or something.

I'll review the actual code soon. Thanks!

2020-06-26 14:20 UTC, ianna commented
> > @jpivarski - please, see the benchmark results on MacOS 10.15.5 (19F101) 2.6 GHz 6-Core Intel Core i7
> 
> These look great!
> 
> The PR accomplished its goal of speeding up operations on big records:
> 
> * Cartesian product with big records (pions and protons): 2.7×
> * Combinations with big records (pions): 8×
> * Combinations with big records (photons): 11× (with the much slower photon selection factored out)
> 
> The reason it was a fix to `RecordArray::carry`, rather than `ak.cartesian` and `ak.combinations`, was so that performance on non-records wouldn't be worsened. But since these weren't changed, they can't be any faster or slower than they were.
> 
> I looked into the one failing test, but I couldn't see what was going on there. I just [triggered a test on master](https://dev.azure.com/jpivarski/Scikit-HEP/_build/results?buildId=2247&view=results) to see if it's some new bug that's crept in due to dependencies changing under us or something.
> 
> I'll review the actual code soon. Thanks!

Thanks, @jpivarski ! Here is the price we pay (`length = 10000`):

Before:
```python
In [97]: arr = ak.Array([[_ for _ in range(length)]])                                                                                        

In [98]: %%timeit         #TEST 3 
    ...: x = ak.combinations(arr, 2) 
    ...:  
    ...:                                                                                                                                     
828 ms ± 11.1 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

In [99]: %%timeit         #TEST 4 
    ...: x = ak.combinations(arr, 2) 
    ...: ak.sum(x) 
    ...:  
    ...:                                                                                                                                     
907 ms ± 19.9 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


```
vs with this PR:
```python
In [73]: arr = ak.Array([[_ for _ in range(length)]])                                                                                        

In [74]: %%timeit         #TEST 3 
    ...: x = ak.combinations(arr, 2) 
    ...:  
    ...:                                                                                                                                     
2.04 s ± 175 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

In [75]: %%timeit         #TEST 4 
    ...: x = ak.combinations(arr, 2) 
    ...: ak.sum(x) 
    ...:  
    ...:                                                                                                                                     
2.06 s ± 197 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


```

2020-06-26 14:25 UTC, jpivarski commented
It looks like a factor of 2 cost, but I don't know why there would be any cost. Maybe it's something else? Nevertheless, I'll be looking at the code soon.

2020-06-26 14:26 UTC, jpivarski commented
> I looked into the one failing test, but I couldn't see what was going on there. I just [triggered a test on master](https://dev.azure.com/jpivarski/Scikit-HEP/_build/results?buildId=2247&view=results) to see if it's some new bug that's crept in due to dependencies changing under us or something.

The master branch is passing, so I [started another on this branch](https://dev.azure.com/jpivarski/Scikit-HEP/_build/results?buildId=2248&view=results).

2020-06-28 12:37 UTC, ianna commented
@jpivarski - Moving back to an eager carry for all except for `ak.combinations` improves its performance, however, there is no improvement for `ak.cartesian`
```python
In [19]: %%timeit 
    ...: pairs = ak.cartesian([events.pions, events.protons]) 
    ...:  
    ...:                                                                                                                                     
69.7 ms ± 2.83 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)

In [20]: %%timeit -n100 -r1  
    ...: pairs = ak.combinations(events.pions, 2, with_name="pair") 
    ...:  
    ...:                                                                                                                                     
12.8 ms ± 0 ns per loop (mean ± std. dev. of 1 run, 100 loops each)

In [21]: evts = events.prt[events.prt.pdg == Particle.from_string("gamma").pdgid]                                                            

In [22]: %%timeit 
    ...: pizero_candidates = ak.combinations(evts, 2, with_name="pair") 
    ...:  
    ...:                                                                                                                                     
12.5 ms ± 213 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

```
on the plus side,  there is no performance degradation here:
```python
In [25]: arr = ak.Array([[_ for _ in range(length)]])                                                                                        

In [26]: %%timeit 
    ...: x = ak.combinations(arr, 2) 
    ...:  
    ...:                                                                                                                                     
812 ms ± 15.8 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

In [27]: %%timeit 
    ...: x = ak.combinations(arr, 2) 
    ...: ak.sum(x) 
    ...:  
    ...:                                                                                                                                     
879 ms ± 27.3 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

```

2020-06-29 15:50 UTC, ianna commented
@jpivarski - finally, everything looks reasonable here:
```python
In [15]: %%timeit  
    ...: pairs = ak.cartesian([events.pions, events.protons])  
    ...:  
    ...:                                                                                                                                     
14.6 ms ± 624 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

In [16]: %%timeit -n100 -r1  
    ...: pairs = ak.combinations(events.pions, 2, with_name="pair")  
    ...:  
    ...:                                                                                                                                     
9.44 ms ± 0 ns per loop (mean ± std. dev. of 1 run, 100 loops each)

In [17]: evts = events.prt[events.prt.pdg == Particle.from_string("gamma").pdgid]                                                            

In [18]: %%timeit  
    ...: pizero_candidates = ak.combinations(evts, 2, with_name="pair") 
    ...:  
    ...:                                                                                                                                     
12.4 ms ± 140 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
```
and here:
```python
In [5]: length=10000                                                                                                                         

In [6]: arr = ak.Array([[_ for _ in range(length)]])                                                                                         

In [7]: %%timeit 
   ...: x = ak.combinations(arr, 2) 
   ...: ak.sum(x) 
   ...:  
   ...:                                                                                                                                      
873 ms ± 8.04 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

In [8]: %%timeit 
   ...: x = ak.combinations(arr, 2) 
   ...:  
   ...:                                                                                                                                      
814 ms ± 11.2 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```

2020-06-30 07:03 UTC, ianna commented on include/awkward/Content.h
> +      carry(const Index64& carry, bool copy = false) const = 0;
Done

2020-06-30 07:04 UTC, ianna commented on tests/test_0025-record-array.py
> +    assert recordarray2[2, "outer"].identity == (0, 'outer') ### (2, "outer")
Done

2020-06-30 07:07 UTC, ianna commented
> It looks like a factor of 2 cost, but I don't know why there would be any cost. Maybe it's something else? Nevertheless, I'll be looking at the code soon.

It was a cost of a dynamic cast put in place as a workaround. It’s not needed any more and was removed.

2020-06-30 07:09 UTC, ianna commented
@jpivarski - I think, the PR is ready for a review :-)

2020-06-30 15:01 UTC, jpivarski approved these changes
This looks great, apart from one correction: the header-file declarations name the new `carry` argument "`must_be_eager`" and the implementations name it "`allow_lazy`", which have opposite meanings:

```bash
% fgrep -r 'carry(' include/
include/awkward/Content.h:      carry(const Index64& carry, bool allow_lazy = false) const = 0;
include/awkward/array/RecordArray.h:      carry(const Index64& carry, bool must_be_eager) const override;
include/awkward/array/IndexedArray.h:      carry(const Index64& carry, bool must_be_eager) const override;
include/awkward/array/None.h:      carry(const Index64& carry, bool must_be_eager) const override;
include/awkward/array/BitMaskedArray.h:      carry(const Index64& carry, bool must_be_eager) const override;
include/awkward/array/NumpyArray.h:      carry(const Index64& carry, bool must_be_eager) const override;
include/awkward/array/UnionArray.h:      carry(const Index64& carry, bool must_be_eager) const override;
include/awkward/array/RawArray.h:      carry(const Index64& carry, bool must_be_eager) const override {
include/awkward/array/RawArray.h:        Index64 nextcarry(lenhead);
include/awkward/array/RawArray.h:        return carry(nextcarry, false);
include/awkward/array/RawArray.h:      return carry(flathead, false);
include/awkward/array/VirtualArray.h:      carry(const Index64& carry, bool must_be_eager) const override;
include/awkward/array/ByteMaskedArray.h:      carry(const Index64& carry, bool must_be_eager) const override;
include/awkward/array/ListOffsetArray.h:      carry(const Index64& carry, bool must_be_eager) const override;
include/awkward/array/ListArray.h:      carry(const Index64& carry, bool must_be_eager) const override;
include/awkward/array/UnmaskedArray.h:      carry(const Index64& carry, bool must_be_eager) const override;
include/awkward/array/Record.h:      carry(const Index64& carry, bool must_be_eager) const override;
include/awkward/array/RegularArray.h:      carry(const Index64& carry, bool must_be_eager) const override;
include/awkward/array/EmptyArray.h:      carry(const Index64& carry, bool must_be_eager) const override;
```

```bash
% fgrep -r '::carry(' src/
src/libawkward/array/ListOffsetArray.cpp:  ListOffsetArrayOf<T>::carry(const Index64& carry, bool allow_lazy) const {
src/libawkward/array/UnionArray.cpp:  UnionArrayOf<T, I>::carry(const Index64& carry, bool allow_lazy) const {
src/libawkward/array/ByteMaskedArray.cpp:  ByteMaskedArray::carry(const Index64& carry, bool allow_lazy) const {
src/libawkward/array/Record.cpp:  Record::carry(const Index64& carry, bool allow_lazy) const {
src/libawkward/array/None.cpp:  None::carry(const Index64& carry, bool allow_lazy) const {
src/libawkward/array/NumpyArray.cpp:  NumpyArray::carry(const Index64& carry, bool allow_lazy) const {
src/libawkward/array/BitMaskedArray.cpp:  BitMaskedArray::carry(const Index64& carry, bool allow_lazy) const {
src/libawkward/array/RecordArray.cpp:  RecordArray::carry(const Index64& carry, bool allow_lazy) const {
src/libawkward/array/IndexedArray.cpp:  IndexedArrayOf<T, ISOPTION>::carry(const Index64& carry, bool allow_lazy) const {
src/libawkward/array/ListArray.cpp:  ListArrayOf<T>::carry(const Index64& carry, bool allow_lazy) const {
src/libawkward/array/EmptyArray.cpp:  EmptyArray::carry(const Index64& carry, bool allow_lazy) const {
src/libawkward/array/UnmaskedArray.cpp:  UnmaskedArray::carry(const Index64& carry, bool allow_lazy) const {
src/libawkward/array/VirtualArray.cpp:  VirtualArray::carry(const Index64& carry, bool allow_lazy) const {
src/libawkward/array/RegularArray.cpp:  RegularArray::carry(const Index64& carry, bool allow_lazy) const {
```

Looking at the implementation of `RecordArray::carry`, it's clear that the true meaning of this parameter is "allow lazy."

https://github.com/scikit-hep/awkward-1.0/blob/c27a4e5c037c9d582a412ee9a6c73c93063b83a1/src/libawkward/array/RecordArray.cpp#L739-L762

which I prefer anyway (shorter to express; easier to think about). But I think I can make that change. I'll put in the next commit and see if the tests still pass.

2020-06-30 16:18 UTC, jpivarski commented
Now I just want to get a handle on the ways `allow_lazy` are used. The parameter is passed down in only 5 classes:

   * VirtualArray
   * UnmaskedArray
   * BitMaskedArray
   * ByteMaskedArray
   * RegularArray

Is there a reason to single out these 5? I just answered my own question: these are the only 5 classes for whom `carry` is not a shallow operation—if any other classes passed `carry` down to their contents, they, too, would pass `allow_lazy` rather than setting it to be a particular value. The one exception to this is that `RecordArray::carry` is not shallow when `allow_lazy = false`, but then forcing `allow_lazy = false` when recursing in `RecordArray::carry` is a tautology.

Fortunately, all the other times that `carry` is called, the `true` or `false` is on the same line (I checked). So all the `trues` are:

```
% fgrep -rn 'carry(' src | fgrep true
src/libawkward/array/ListOffsetArray.cpp:285:    ContentPtr nextcontent = content_.get()->carry(nextcarry, true);
src/libawkward/array/ListOffsetArray.cpp:1474:      ContentPtr nextcontent = content_.get()->carry(nextcarry, true);
src/libawkward/array/ListOffsetArray.cpp:1664:        contents.push_back(content_.get()->carry(Index64(ptr, 0, totallen), true));
src/libawkward/array/ListOffsetArray.cpp:2037:    ContentPtr nextcontent = content_.get()->carry(nextcarry, true);
src/libawkward/array/ListOffsetArray.cpp:2086:    ContentPtr nextcontent = content_.get()->carry(nextcarry, true);
src/libawkward/array/ListOffsetArray.cpp:2145:      ContentPtr nextcontent = content_.get()->carry(nextcarry, true);
src/libawkward/array/ListOffsetArray.cpp:2169:      ContentPtr nextcontent = content_.get()->carry(nextcarry, true);
src/libawkward/array/UnionArray.cpp:661:      return contents[0].get()->carry(index, true);
src/libawkward/array/ByteMaskedArray.cpp:1039:      ContentPtr next = content_.get()->carry(nextcarry, true);
src/libawkward/array/IndexedArray.cpp:363:      return content_.get()->carry(nextcarry, true);
src/libawkward/array/IndexedArray.cpp:1144:        ContentPtr next = content_.get()->carry(nextcarry, true);
src/libawkward/array/IndexedArray.cpp:1162:        ContentPtr next = content_.get()->carry(nextcarry, true);
src/libawkward/array/IndexedArray.cpp:1283:      ContentPtr next = content_.get()->carry(nextcarry, true);
src/libawkward/array/IndexedArray.cpp:1310:      ContentPtr next = content_.get()->carry(nextcarry, true);
src/libawkward/array/IndexedArray.cpp:1668:      ContentPtr next = content_.get()->carry(nextcarry, true);
src/libawkward/array/IndexedArray.cpp:1861:    ContentPtr next = content_.get()->carry(nextcarry, true);
src/libawkward/array/IndexedArray.cpp:1929:        ContentPtr next = content_.get()->carry(nextcarry, true);
src/libawkward/array/IndexedArray.cpp:1965:        ContentPtr next = content_.get()->carry(nextcarry, true);
src/libawkward/array/IndexedArray.cpp:2285:      ContentPtr next = content_.get()->carry(nextcarry, true);
src/libawkward/array/IndexedArray.cpp:2306:      ContentPtr next = content_.get()->carry(nextcarry, true);
src/libawkward/array/ListArray.cpp:1360:        contents.push_back(content_.get()->carry(Index64(ptr, 0, totallen), true));
src/libawkward/array/RegularArray.cpp:230:      ContentPtr nextcontent = content_.get()->carry(nextcarry, true);
src/libawkward/array/RegularArray.cpp:983:        contents.push_back(content_.get()->carry(Index64(ptr, 0, totallen), true));
src/libawkward/array/RegularArray.cpp:1203:      ContentPtr nextcontent = content_.get()->carry(nextcarry, true);
src/libawkward/array/RegularArray.cpp:1225:      ContentPtr nextcontent = content_.get()->carry(nextcarry, true);
```

and all the `falses` are

```
% fgrep -rn 'carry(' src | fgrep false
src/libawkward/array/ListOffsetArray.cpp:1790:      ContentPtr nextcontent = content_.get()->carry(nextcarry, false);
src/libawkward/array/ListOffsetArray.cpp:1804:      outcontent = outcontent.get()->carry(outcarry, false);
src/libawkward/array/ListOffsetArray.cpp:1945:      ContentPtr nextcontent = content_.get()->carry(nextcarry, false);
src/libawkward/array/ListOffsetArray.cpp:1959:      outcontent = outcontent.get()->carry(outcarry, false);
src/libawkward/array/UnionArray.cpp:431:    return contents_[(size_t)index].get()->carry(nextcarry, false);
src/libawkward/array/ByteMaskedArray.cpp:223:    return content_.get()->carry(nextcarry, false);
src/libawkward/array/ByteMaskedArray.cpp:610:      ContentPtr next = content_.get()->carry(nextcarry, false);
src/libawkward/array/ByteMaskedArray.cpp:659:                                             content_.get()->carry(carry, false),
src/libawkward/array/ByteMaskedArray.cpp:712:      ContentPtr next = content_.get()->carry(nextcarry, false);
src/libawkward/array/ByteMaskedArray.cpp:735:      ContentPtr next = content_.get()->carry(nextcarry, false);
src/libawkward/array/ByteMaskedArray.cpp:944:    ContentPtr next = content_.get()->carry(nextcarry, false);
src/libawkward/array/ByteMaskedArray.cpp:1009:      ContentPtr next = content_.get()->carry(nextcarry, false);
src/libawkward/array/ByteMaskedArray.cpp:1086:    ContentPtr next = content_.get()->carry(nextcarry, false);
src/libawkward/array/ByteMaskedArray.cpp:1171:    ContentPtr next = content_.get()->carry(nextcarry, false);
src/libawkward/array/ByteMaskedArray.cpp:1300:      ContentPtr next = content_.get()->carry(nextcarry, false);
src/libawkward/array/RecordArray.cpp:754:        contents.push_back(content.get()->carry(carry, false));
src/libawkward/array/IndexedArray.cpp:375:      return content_.get()->carry(nextcarry, false);
src/libawkward/array/IndexedArray.cpp:2020:    ContentPtr next = content_.get()->carry(nextcarry, false);
src/libawkward/array/IndexedArray.cpp:2123:    ContentPtr next = content_.get()->carry(nextcarry, false);
src/libawkward/array/ListArray.cpp:266:    ContentPtr nextcontent = content_.get()->carry(nextcarry, false);
src/libawkward/array/ListArray.cpp:1456:    ContentPtr nextcontent = content_.get()->carry(nextcarry, false);
src/libawkward/array/ListArray.cpp:1510:    ContentPtr nextcontent = content_.get()->carry(nextcarry, false);
src/libawkward/array/ListArray.cpp:1574:      ContentPtr nextcontent = content_.get()->carry(nextcarry, false);
src/libawkward/array/ListArray.cpp:1598:      ContentPtr nextcontent = content_.get()->carry(nextcarry, false);
src/libawkward/array/ListArray.cpp:1637:    ContentPtr carried = content_.get()->carry(nextcarry, false);
src/libawkward/array/ListArray.cpp:1700:    ContentPtr nextcontent = content_.get()->carry(nextcarry, false);
src/libawkward/array/ListArray.cpp:1758:      ContentPtr nextcontent = content_.get()->carry(nextcarry, false);
src/libawkward/array/RegularArray.cpp:1093:    ContentPtr nextcontent = content_.get()->carry(nextcarry, false);
src/libawkward/array/RegularArray.cpp:1145:    ContentPtr nextcontent = content_.get()->carry(nextcarry, false);
```

To be more specific, `carry` is only used with `allow_lazy = true` in the following situations:

   * **A:** `ByteMaskedArray::combinations`.
   * **A:** `IndexedArray::combinations`.
   * **A:** `ListArray::combinations`.
   * **A:** `ListOffsetArray::combinations`.
   * **A:** `RegularArray::combinations`.
   * **A:** In fact, every class whose `combinations` implementation calls `carry` does so with `allow_lazy = true`. Good.
   * **B:** `IndexedArray::project`, but only when it's option-type. This is the minimum required to break recursion: if `broadcast_and_apply` (on the Python side) is opening up an IndexedOptionArray containing a RecordArray, the first step would turn it into an IndexedArray of RecordArray and the next step would turn it into a RecordArray (because `IndexedArray::project` is eager when not option-type). But if the default policy is to be eager, only lazily carrying in `combinations`, then perhaps `IndexedArray::project` should be simplified to only be eager like everything else.
   * **B:** `IndexedArray::num` (both). Same argument.
   * [...]

2020-06-30 16:36 UTC, jpivarski commented
Of the `getitem_next` (cases **E** above), only the following are relevant (non-trivial implementation that calls `carry`):

   * `ByteMaskedArray:getitem_next` (centralized method). Currently, it uses **eager carry**.
   * `RegularArray::getitem_next` (decentralized: looking at `SliceAt`, `SliceRange`, `SliceArray`). Currently, it uses **eager carry**.
   * `IndexedArray::getitem_next` (centralized). Currently, it uses **lazy carry**.
   * `ListOffsetArray::getitem_next` (decentralized). Currently, it uses **lazy carry**.
   * `ListArray::getitem_next` (decentralized). Currently, it uses **eager carry**.

I'm going to try making all get-items of `SliceAt`, `SliceRange`, and `SliceArray` use a **lazy carry** (`allow_lazy = true`).

2020-06-30 19:46 UTC, jpivarski commented
@ianna I think it's done. Thanks for all your work on this!

I may have invalidated your latest timing measurements, but probably not by much because I left the laziness on in `ak.combinations`. With laziness turned on in all cases of `broadcast_tooffsets64`, the `ak.cartesian` function (which takes two arguments, but is otherwise similar to `ak.combinations`) is now fully lazy as well, which should give it a similar performance boost as `ak.combinations`. At least, they have the same form (the `x`/`y` RecordArray below is wrapped in IndexedArray as a result of the operation—no expensive carrying of wide records):

```python
>>> import awkward1 as ak
>>> records = ak.Array([[{"x": 1.1, "y": 100}, {"x": 2.2, "y": 200}, {"x": 3.3, "y": 300}],
...                    [],
...                    [{"x": 4.4, "y": 400}, {"x": 5.5, "y": 500}]])
>>> records.layout.form
{
    "class": "ListOffsetArray64",
    "offsets": "i64",
    "content": {
        "class": "RecordArray",
        "contents": {
            "x": "float64",
            "y": "int64"
        }
    }
}
>>> ak.combinations(records, 2).layout.form
{
    "class": "ListOffsetArray64",
    "offsets": "i64",
    "content": {
        "class": "RecordArray",
        "contents": [
            {
                "class": "IndexedArray64",
                "index": "i64",
                "content": {
                    "class": "RecordArray",
                    "contents": {
                        "x": "float64",
                        "y": "int64"
                    }
                }
            },
            {
                "class": "IndexedArray64",
                "index": "i64",
                "content": {
                    "class": "RecordArray",
                    "contents": {
                        "x": "float64",
                        "y": "int64"
                    }
                }
            }
        ]
    }
}
>>> ak.cartesian([records, records]).layout.form
{
    "class": "ListOffsetArray64",
    "offsets": "i64",
    "content": {
        "class": "RecordArray",
        "contents": [
            {
                "class": "IndexedArray64",
                "index": "i64",
                "content": {
                    "class": "RecordArray",
                    "contents": {
                        "x": "float64",
                        "y": "int64"
                    }
                }
            },
            {
                "class": "IndexedArray64",
                "index": "i64",
                "content": {
                    "class": "RecordArray",
                    "contents": {
                        "x": "float64",
                        "y": "int64"
                    }
                }
            }
        ]
    }
}
```

Having this extra handle will give us the leverage to tune performance wherever users raise the issue. Thanks!

2020-06-30 19:56 UTC, merged

2020-06-30 20:40 UTC, ianna commented
Thank you @jpivarski !!!

2020-07-01 07:17 UTC, ianna commented
@jpivarski - the final numbers look great! Thanks!
Here is the master:
```python
In [33]: %%timeit -n1000 -r1 
    ...: pairs = ak.cartesian([events.pions, events.protons], with_name="pair") 
    ...:  
    ...:                                                                                                                                     
7.93 ms ± 0 ns per loop (mean ± std. dev. of 1 run, 1000 loops each)

In [34]: %%timeit -n100 -r1 
    ...: pairs = ak.combinations(events.pions, 2, with_name="pair")  
    ...:  
    ...:                                                                                                                                     
16.4 ms ± 0 ns per loop (mean ± std. dev. of 1 run, 100 loops each)

In [35]: %%timeit  
    ...: pizero_candidates = ak.combinations(events.prt[events.prt.pdg == Particle.from_string("gamma").pdgid], 2, with_name="pair")  
    ...:  
    ...:                                                                                                                                     
269 ms ± 3.66 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

In [36]: evts = events.prt[events.prt.pdg == Particle.from_string("gamma").pdgid]                                                            

In [37]: %%timeit  
    ...: pizero_candidates = ak.combinations(evts, 2, with_name="pair") 
    ...:  
    ...:                                                                                                                                     
25.1 ms ± 472 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)

In [38]: %%timeit 
    ...: pizero_candidates = ak.combinations(events.prt[events.prt.pdg == Particle.from_string("gamma").pdgid], 2, with_name="pair") 
    ...: pizero = pizero_candidates[pizero_candidates.mass(0, 0) - 0.13498 < 0.000001]  
    ...: pizero["px"] = pizero.slot0.px + pizero.slot1.px  
    ...: pizero["py"] = pizero.slot0.py + pizero.slot1.py  
    ...: pizero["pz"] = pizero.slot0.pz + pizero.slot1.pz 
    ...: pizero["p"] = np.sqrt(pizero.px**2 + pizero.py**2 + pizero.pz**2)  
    ...:  
    ...:                                                                                                                                     
1.08 s ± 22.1 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```
and before:
```python
In [72]: %%timeit -n1000 -r1 
    ...: pairs = ak.cartesian([events.pions, events.protons], with_name="pair") 
    ...:  
    ...:                                                                                                                                     
67.4 ms ± 0 ns per loop (mean ± std. dev. of 1 run, 1000 loops each)

In [80]: %%timeit -n100 -r1 
    ...: pairs = ak.combinations(events.pions, 2, with_name="pair") 
    ...:  
    ...:                                                                                                                                     
356 ms ± 0 ns per loop (mean ± std. dev. of 1 run, 100 loops each)

In [83]: %%timeit 
    ...: pizero_candidates = ak.combinations(events.prt[events.prt.pdg == Particle.from_string("gamma").pdgid], 2, with_name="pair") 
    ...:  
    ...:                                                                                                                                     
830 ms ± 14.7 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

In [85]: evts = events.prt[events.prt.pdg == Particle.from_string("gamma").pdgid]                                                            

In [86]: %%timeit 
    ...: pizero_candidates = ak.combinations(evts, 2, with_name="pair") 
    ...:  
    ...:                                                                                                                                     
551 ms ± 2 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

In [94]: %%timeit 
    ...: pizero_candidates = ak.combinations(events.prt[events.prt.pdg == Particle.from_string("gamma").pdgid], 2, with_name="pair") 
    ...: pizero = pizero_candidates[pizero_candidates.mass(0, 0) - 0.13498 < 0.000001] 
    ...: pizero["px"] = pizero.slot0.px + pizero.slot1.px 
    ...: pizero["py"] = pizero.slot0.py + pizero.slot1.py 
    ...: pizero["pz"] = pizero.slot0.pz + pizero.slot1.pz 
    ...: pizero["p"] = np.sqrt(pizero.px**2 + pizero.py**2 + pizero.pz**2) 
    ...:  
    ...:                                                                                                                                     
2.24 s ± 36.8 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```
There is no change in here:
```python
In [19]: length=10000                                                                                                                        

In [20]: arr = ak.Array([[_ for _ in range(length)]])                                                                                        

In [21]: %%timeit  
    ...: x = ak.combinations(arr, 2)  
    ...:  
    ...:                                                                                                                                     
851 ms ± 7.37 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

In [22]: %%timeit 
    ...: x = ak.combinations(arr, 2)  
    ...: ak.sum(x)  
    ...:  
    ...:                                                                                                                                     
910 ms ± 8.88 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```

before:
```python
In [97]: arr = ak.Array([[_ for _ in range(length)]])                                                                                        

In [98]: %%timeit
    ...: x = ak.combinations(arr, 2) 
    ...:  
    ...:                                                                                                                                     
828 ms ± 11.1 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

In [99]: %%timeit 
    ...: x = ak.combinations(arr, 2) 
    ...: ak.sum(x) 
    ...:  
    ...:                                                                                                                                     
907 ms ± 19.9 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```