feat: add string builder
scikit-hep/awkward pull request #2899
Opened 2023-12-14 16:41 UTC by lobis

Add a string builder to the header-only library to make building arrays of strings easier.

2023-12-14 17:01 UTC, ianna requested changes
@lobis - looks great! I don't think `clang-format` was run. Could you please run it by hand? Thanks!

2023-12-14 17:01 UTC, ianna commented on header-only/layout-builder/awkward/LayoutBuilder.h
> +      this->set_parameters(R"""("__array__": "string")""");
@lobis - please, make sure to run `clang-format`

2023-12-14 17:01 UTC, ianna commented on header-only/layout-builder/awkward/LayoutBuilder.h
> +        for (const auto c: value) {
```suggestion
        for (const auto& c: value) {
```

2023-12-14 17:14 UTC, lobis commented
By the way I noticed that there is not `clang-format` in the pre-commit

> @lobis - looks great! I don't think `clang-format` was run. Could you please run it by hand? Thanks!

Yes I noticed, I'll run by hand, but isn't it supposed to be run automatically be pre-commit? I tried to add `clang-format` to the pre-commit config but there are some issues with it.

2024-01-29 10:29 UTC, ianna approved these changes
@lobis - Thanks, it looks good to me.

2024-01-29 17:49 UTC, jpivarski approved these changes
Great, thanks! I approve it as well.

I'm pretty sure this will automatically pass all of the test (unless there's a C++ compilation error or something).

Is it ready to merge, assuming that it does pass tests?

2024-01-29 18:22 UTC, lobis commented
> Great, thanks! I approve it as well.
> 
> I'm pretty sure this will automatically pass all of the test (unless there's a C++ compilation error or something).
> 
> Is it ready to merge, assuming that it does pass tests?

Ready!

2024-01-29 19:15 UTC, merged

2024-02-02 19:26 UTC, jpivarski commented
@all-contributors please add @lobis for code