Adding support for numpy.real, imag, round, angle,
scikit-hep/awkward pull request #3053
Opened 2024-03-15 01:22 UTC by tcawlfield

Closes #2917

This issue does not mention round explicitly. and it does mention around which I have not duplicated yet.
I could additionally implement `numpy.fix` and `real_if_close`.

There is an error in my attempt to support the `out=<array>` optional argument -- see discussion.

2024-03-15 01:23 UTC, tcawlfield commented
Are there automatic code formatters and formatting checks? I guess I'll find out! Oh, I did find out and there are indeed.

2024-03-15 01:52 UTC, ianna commented
> Are there automatic code formatters and formatting checks? I guess I'll find out! Oh, I did find out and there are indeed.

Indeed, they are. You can run `pre-commit run --all` and fix the warnings before pushing then you will not need to pull the automatically updated branch from remote.

2024-03-15 15:53 UTC, jpivarski commented
We don't yet have automatic code formatting on C++, but ~~black~~ ruff auto-formats Python. (And some other things in pre-commit format YAML and TOML.) We've talked about formatting C++ (#34, #1865, #2902), but never converged.

I agree with @ianna that it's more convenient to run pre-commit locally, since formatting changes can automatically write new commits to the PR, and then if you commit on your local clone, you've got a conflict to manage.

2024-03-15 16:01 UTC, jpivarski requested changes
This implements `real`, `imag`, `angle`, and `round` as NEP-18 overloads, since they're not ufuncs like `np.floor`:

```python
>>> np.real
<function real at 0x70646be60d70>
>>> np.imag
<function imag at 0x70646be613f0>
>>> np.angle
<function angle at 0x7063e9b4ac30>
>>> np.round
<function round at 0x70646bfd3eb0>
>>> np.floor
<ufunc 'floor'>
```

Overall, it looks good; I just have a few inline requested changes.

2024-03-15 16:01 UTC, jpivarski commented on src/awkward/_nplikes/typetracer.py
> +}
This works, although it reproduces some logic that exists in NumPy, and our main concern is to make Awkward do the same thing that NumPy does, whatever that is. Also, this uses some non-standard names, like `"single"`, `"double"`, and `"longdouble"`; in this codebase, we would always say `np.float32`, `np.float64`, and `np.float128` (if it exists; [it's platform-dependent](https://github.com/scikit-hep/awkward/blob/dfc9690537386ab690c7e7de1baa8e6b041632be/src/awkward/types/numpytype.py#L87-L88)).

Here's a way to get NumPy to tell us how it convert a complex dtype `dt` into the corresponding real dtype:

```python
np.real(np.zeros(0, dtype=dt)).dtype
```

2024-03-15 16:01 UTC, jpivarski commented on src/awkward/_nplikes/typetracer.py
> +            result_type = _real_parts_of.get(x.dtype, x.dtype)
Similar to the above, it looks like you're trying to encode type conversion rules that NumPy already implements. If this is platform-dependent, it's one that NumPy will likely change in NumPy 2.0. But you can use the same trick for `np.angle` as `np.real`.

2024-03-15 16:01 UTC, jpivarski commented on src/awkward/operations/ak_real_imag_angle.py
> +# BSD 3-Clause License; see https://github.com/scikit-hep/awkward/blob/main/LICENSE
Even if it looks wasteful, let's keep it as one Python file per high-level function (so, 3 files in this case).

2024-03-15 18:32 UTC, agoose77 commented on src/awkward/operations/ak_real_imag_angle.py
> +# BSD 3-Clause License; see https://github.com/scikit-hep/awkward/blob/main/LICENSE
Ooh, I missed this on mobile!

2024-03-20 19:11 UTC, jpivarski commented
Let me know when you want me to re-review this!

2024-03-20 22:11 UTC, jpivarski approved these changes

2024-03-20 22:12 UTC, jpivarski commented
Great, thanks! This one is done and I'll merge it.

2024-03-20 22:28 UTC, merged

2024-04-01 18:24 UTC, jpivarski commented
@all-contributors please add @tcawlfield for code