feat: add reduce kernels
scikit-hep/awkward pull request #3136
Opened 2024-05-30 13:38 UTC by ManasviGoyal

2024-06-06 13:23 UTC, lgray commented
@ManasviGoyal in trying to implement query 4 from the analysis benchmarks I found some nasty memory scaling:

If you scroll to the bottom of the trace below you'll see that for attemping to execute:
<img width="461" alt="image" src="https://github.com/scikit-hep/awkward/assets/1068089/45dea563-b5b9-4d15-8571-45738e2e0bb3">

This is processing ~60M rows all at once in the input file, the data fit with no problem in the GPU itself. Same for the histogram that is being filled. 

However, for the ak.sum, where the calculation fails, it is attempting to allocation 71 **terabytes** of ram on the device. This seems excessive and is indicative of some poor memory scaling properties in the implementation. You'll see that this fails in the `ak.sum` step and nowhere else.

Here's the full stack trace:
```
---------------------------------------------------------------------------
OutOfMemoryError                          Traceback (most recent call last)
Cell In[3], line 16
     11 MET_pt = ak.to_backend(jetmet.MET_pt, "cuda")
     12 q4_hist = hist.Hist(
     13     "Counts",
     14     hist.Bin("met", "$E_{T}^{miss}$ [GeV]", 100, 0, 200),
     15 )
---> 16 has2jets = ak.sum(Jet_pt > 40, axis=1) >= 2
     17 q4_hist.fill(met=MET_pt[has2jets])
     19 q4_hist.to_hist().plot1d(flow="none");

File [~/coffea-gpu/awkward/src/awkward/_dispatch.py:64](https://analytics-hub.fnal.gov/user/lagray/lab/tree/coffea-gpu/coffea-gpu/awkward/src/awkward/_dispatch.py#line=63), in named_high_level_function.<locals>.dispatch(*args, **kwargs)
     62 # Failed to find a custom overload, so resume the original function
     63 try:
---> 64     next(gen_or_result)
     65 except StopIteration as err:
     66     return err.value

File [~/coffea-gpu/awkward/src/awkward/operations/ak_sum.py:210](https://analytics-hub.fnal.gov/user/lagray/lab/tree/coffea-gpu/coffea-gpu/awkward/src/awkward/operations/ak_sum.py#line=209), in sum(array, axis, keepdims, mask_identity, highlevel, behavior, attrs)
    207 yield (array,)
    209 # Implementation
--> 210 return _impl(array, axis, keepdims, mask_identity, highlevel, behavior, attrs)

File [~/coffea-gpu/awkward/src/awkward/operations/ak_sum.py:277](https://analytics-hub.fnal.gov/user/lagray/lab/tree/coffea-gpu/coffea-gpu/awkward/src/awkward/operations/ak_sum.py#line=276), in _impl(array, axis, keepdims, mask_identity, highlevel, behavior, attrs)
    274     layout = ctx.unwrap(array, allow_record=False, primitive_policy="error")
    275 reducer = ak._reducers.Sum()
--> 277 out = ak._do.reduce(
    278     layout,
    279     reducer,
    280     axis=axis,
    281     mask=mask_identity,
    282     keepdims=keepdims,
    283     behavior=ctx.behavior,
    284 )
    285 return ctx.wrap(out, highlevel=highlevel, allow_other=True)

File [~/coffea-gpu/awkward/src/awkward/_do.py:333](https://analytics-hub.fnal.gov/user/lagray/lab/tree/coffea-gpu/coffea-gpu/awkward/src/awkward/_do.py#line=332), in reduce(layout, reducer, axis, mask, keepdims, behavior)
    331 parents = ak.index.Index64.zeros(layout.length, layout.backend.index_nplike)
    332 shifts = None
--> 333 next = layout._reduce_next(
    334     reducer,
    335     negaxis,
    336     starts,
    337     shifts,
    338     parents,
    339     1,
    340     mask,
    341     keepdims,
    342     behavior,
    343 )
    345 return next[0]

File [~/coffea-gpu/awkward/src/awkward/contents/listoffsetarray.py:1612](https://analytics-hub.fnal.gov/user/lagray/lab/tree/coffea-gpu/coffea-gpu/awkward/src/awkward/contents/listoffsetarray.py#line=1611), in ListOffsetArray._reduce_next(self, reducer, negaxis, starts, shifts, parents, outlength, mask, keepdims, behavior)
   1609 trimmed = self._content[self.offsets[0] : self.offsets[-1]]
   1610 nextstarts = self.offsets[:-1]
-> 1612 outcontent = trimmed._reduce_next(
   1613     reducer,
   1614     negaxis,
   1615     nextstarts,
   1616     shifts,
   1617     nextparents,
   1618     globalstarts_length,
   1619     mask,
   1620     keepdims,
   1621     behavior,
   1622 )
   1624 outoffsets = Index64.empty(outlength + 1, index_nplike)
   1625 assert outoffsets.nplike is index_nplike and parents.nplike is index_nplike

File [~/coffea-gpu/awkward/src/awkward/contents/numpyarray.py:1122](https://analytics-hub.fnal.gov/user/lagray/lab/tree/coffea-gpu/coffea-gpu/awkward/src/awkward/contents/numpyarray.py#line=1121), in NumpyArray._reduce_next(self, reducer, negaxis, starts, shifts, parents, outlength, mask, keepdims, behavior)
   1119 assert self.is_contiguous
   1120 assert self._data.ndim == 1
-> 1122 out = reducer.apply(self, parents, starts, shifts, outlength)
   1124 if mask:
   1125     outmask = ak.index.Index8.empty(outlength, self._backend.index_nplike)

File [~/coffea-gpu/awkward/src/awkward/_reducers.py:358](https://analytics-hub.fnal.gov/user/lagray/lab/tree/coffea-gpu/coffea-gpu/awkward/src/awkward/_reducers.py#line=357), in Sum.apply(self, array, parents, starts, shifts, outlength)
    355 if result.dtype in (np.int64, np.uint64):
    356     assert parents.nplike is array.backend.index_nplike
    357     array.backend.maybe_kernel_error(
--> 358         array.backend[
    359             "awkward_reduce_sum_int64_bool_64",
    360             np.int64,
    361             array.dtype.type,
    362             parents.dtype.type,
    363         ](
    364             result,
    365             array.data,
    366             parents.data,
    367             parents.length,
    368             outlength,
    369         )
    370     )
    371 elif result.dtype in (np.int32, np.uint32):
    372     assert parents.nplike is array.backend.index_nplike

File [~/coffea-gpu/awkward/src/awkward/_kernels.py:169](https://analytics-hub.fnal.gov/user/lagray/lab/tree/coffea-gpu/coffea-gpu/awkward/src/awkward/_kernels.py#line=168), in CupyKernel.__call__(self, *args)
    157 args = (
    158     *args,
    159     len(ak_cuda.cuda_streamptr_to_contexts[cupy_stream_ptr][1]),
    160     ak_cuda.cuda_streamptr_to_contexts[cupy_stream_ptr][0],
    161 )
    162 ak_cuda.cuda_streamptr_to_contexts[cupy_stream_ptr][1].append(
    163     ak_cuda.Invocation(
    164         name=self.key[0],
    165         error_context=ak._errors.ErrorContext.primary(),
    166     )
    167 )
--> 169 self._impl(grid, blocks, args)

File [~/coffea-gpu/awkward/src/awkward/_connect/cuda/_kernel_signatures.py:4337](https://analytics-hub.fnal.gov/user/lagray/lab/tree/coffea-gpu/coffea-gpu/awkward/src/awkward/_connect/cuda/_kernel_signatures.py#line=4336), in by_signature.<locals>.f(grid, block, args)
   4335     segment = 0
   4336     grid_size = 1
-> 4337 partial = cupy.zeros(outlength * grid_size, dtype=toptr.dtype)
   4338 temp = cupy.zeros(lenparents, dtype=toptr.dtype)
   4339 cuda_kernel_templates.get_function(fetch_specialization(["awkward_reduce_sum_int64_bool_64_a", int64, bool_, parents.dtype]))((grid_size,), block, (toptr, fromptr, parents, lenparents, outlength, partial, temp, invocation_index, err_code))

File ~/.conda/envs/coffea-gpu/lib/python3.12/site-packages/cupy/_creation/basic.py:248, in zeros(shape, dtype, order)
    229 def zeros(
    230         shape: _ShapeLike,
    231         dtype: DTypeLike = float,
    232         order: _OrderCF = 'C',
    233 ) -> NDArray[Any]:
    234     """Returns a new array of given shape and dtype, filled with zeros.
    235 
    236     Args:
   (...)
    246 
    247     """
--> 248     a = cupy.ndarray(shape, dtype, order=order)
    249     a.data.memset_async(0, a.nbytes)
    250     return a

File cupy[/_core/core.pyx:132](https://analytics-hub.fnal.gov/_core/core.pyx#line=131), in cupy._core.core.ndarray.__new__()

File cupy[/_core/core.pyx:220](https://analytics-hub.fnal.gov/_core/core.pyx#line=219), in cupy._core.core._ndarray_base._init()

File cupy[/cuda/memory.pyx:738](https://analytics-hub.fnal.gov/cuda/memory.pyx#line=737), in cupy.cuda.memory.alloc()

File cupy[/cuda/memory.pyx:1424](https://analyt [...]

2024-06-06 14:34 UTC, ManasviGoyal commented
> @ManasviGoyal in trying to implement query 4 from the analysis benchmarks I found some nasty memory scaling:
> 
> If you scroll to the bottom of the trace below you'll see that when attempting to execute: <img alt="image" width="461" src="https://private-user-images.githubusercontent.com/1068089/337276285-45dea563-b5b9-4d15-8571-45738e2e0bb3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc2ODQ2NTgsIm5iZiI6MTcxNzY4NDM1OCwicGF0aCI6Ii8xMDY4MDg5LzMzNzI3NjI4NS00NWRlYTU2My1iNWI5LTRkMTUtODU3MS00NTczOGUyZTBiYjMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYwNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MDZUMTQzMjM4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTI4NmIwYjI5ODQ1MDg2MDMzNzhjMTUwNmJkMjAyZTcyOTNhNDhmNWI3ZjA5OTZhZmE3NmMxZjMxYzhlODIyMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.uuXM_4VeXpKnyIr6_qHO9LugvsTJ7uAWUTCZ57dTz8Q">
> 
> This is processing ~53M rows all at once in the input file, the data fit with no problem in the GPU itself. Same for the histogram that is being filled.
> 
> For this test I have merged #3123, #3142, and this PR on top of awkward main. This PR was merged in last.
> 
> However, for the ak.sum, where the calculation fails, it is attempting to allocation 71 **terabytes** of ram on the device. This seems excessive and is indicative of some poor memory scaling properties in the implementation. You'll see that this fails in the `ak.sum` step and nowhere else.
> 
> Here's the full stack trace:
> 
> ```
> ---------------------------------------------------------------------------
> OutOfMemoryError                          Traceback (most recent call last)
> Cell In[3], line 16
>      11 MET_pt = ak.to_backend(jetmet.MET_pt, "cuda")
>      12 q4_hist = hist.Hist(
>      13     "Counts",
>      14     hist.Bin("met", "$E_{T}^{miss}$ [GeV]", 100, 0, 200),
>      15 )
> ---> 16 has2jets = ak.sum(Jet_pt > 40, axis=1) >= 2
>      17 q4_hist.fill(met=MET_pt[has2jets])
>      19 q4_hist.to_hist().plot1d(flow="none");
> 
> File [~/coffea-gpu/awkward/src/awkward/_dispatch.py:64](https://analytics-hub.fnal.gov/user/lagray/lab/tree/coffea-gpu/coffea-gpu/awkward/src/awkward/_dispatch.py#line=63), in named_high_level_function.<locals>.dispatch(*args, **kwargs)
>      62 # Failed to find a custom overload, so resume the original function
>      63 try:
> ---> 64     next(gen_or_result)
>      65 except StopIteration as err:
>      66     return err.value
> 
> File [~/coffea-gpu/awkward/src/awkward/operations/ak_sum.py:210](https://analytics-hub.fnal.gov/user/lagray/lab/tree/coffea-gpu/coffea-gpu/awkward/src/awkward/operations/ak_sum.py#line=209), in sum(array, axis, keepdims, mask_identity, highlevel, behavior, attrs)
>     207 yield (array,)
>     209 # Implementation
> --> 210 return _impl(array, axis, keepdims, mask_identity, highlevel, behavior, attrs)
> 
> File [~/coffea-gpu/awkward/src/awkward/operations/ak_sum.py:277](https://analytics-hub.fnal.gov/user/lagray/lab/tree/coffea-gpu/coffea-gpu/awkward/src/awkward/operations/ak_sum.py#line=276), in _impl(array, axis, keepdims, mask_identity, highlevel, behavior, attrs)
>     274     layout = ctx.unwrap(array, allow_record=False, primitive_policy="error")
>     275 reducer = ak._reducers.Sum()
> --> 277 out = ak._do.reduce(
>     278     layout,
>     279     reducer,
>     280     axis=axis,
>     281     mask=mask_identity,
>     282     keepdims=keepdims,
>     283     behavior=ctx.behavior,
>     284 )
>     285 return ctx.wrap(out, highlevel=highlevel, allow_other=True)
> 
> File [~/coffea-gpu/awkward/src/awkward/_do.py:333](https://analytics-hub.fnal.gov/user/lagray/lab/tree/coffea-gpu/coffea-gpu/awkward/src/awkward/_do.py#line=332), in reduce(layout, reducer, axis, mask, keepdims, behavior)
>     331 parents = ak.index.Index64.zeros(layout.length, layout.backend.index_nplike)
>     332 shifts = None
> --> 333 next = layout._reduce_next(
>     334     reducer,
>     335     negaxis,
>     336     starts,
>     337     shifts,
>     338     parents,
>     339     1,
>     340     mask,
>     341     keepdims,
>     342     behavior,
>     343 )
>     345 return next[0]
> 
> File [~/coffea-gpu/awkward/src/awkward/contents/listoffsetarray.py:1612](https://analytics-hub.fnal.gov/user/lagray/lab/tree/coffea-gpu/coffea-gpu/awkward/src/awkward/contents/listoffsetarray.py#line=1611), in ListOffsetArray._reduce_next(self, reducer, negaxis, starts, shifts, parents, outlength, mask, keepdims, behavior)
>    1609 trimmed = self._content[self.offsets[0] : self.offsets[-1]]
>    1610 nextstarts = self.offsets[:-1]
> -> 1612 outcontent = trimmed._reduce_next(
>    1613     reducer,
>    1614     negaxis,
>    1615     nextstarts,
>    1616     shifts,
>    1617     nextparents,
>    1618     globalstarts_length,
>    1619     mask,
>    1620     keepdims,
>    1621     behavior,
>    1622 )
>    1624 outoffsets = Index64.empty(outlength + 1, index_nplike)
>    1625 assert outoffsets.nplike is index_nplike and parents.nplike is index_nplike
> 
> File [~/coffea-gpu/awkward/src/awkward/contents/numpyarray.py:1122](https://analytics-hub.fnal.gov/user/lagray/lab/tree/coffea-gpu/coffea-gpu/awkward/src/awkward/contents/numpyarray.py#line=1121), in NumpyArray._reduce_next(self, reducer, negaxis, starts, shifts, parents, outlength, mask, keepdims, behavior)
>    1119 assert self.is_contiguous
>    1120 assert self._data.ndim == 1
> -> 1122 out = reducer.apply(self, parents, starts, shifts, outlength)
>    1124 if mask:
>    1125     outmask = ak.index.Index8.empty(outlength, self._backend.index_nplike)
> 
> File [~/coffea-gpu/awkward/src/awkward/_reducers.py:358](https://analytics-hub.fnal.gov/user/lagray/lab/tree/coffea-gpu/coffea-gpu/awkward/src/awkward/_reducers.py#line=357), in Sum.apply(self, array, parents, starts, shifts, outlength)
>     355 if result.dtype in (np.int64, np.uint64):
>     356     assert parents.nplike is array.backend.index_nplike
>     357     array.backend.maybe_kernel_error(
> --> 358         array.backend[
>     359             "awkward_reduce_sum_int64_bool_64",
>     360             np.int64,
>     361             array.dtype.type,
>     362             parents.dtype.type,
>     363         ](
>     364             result,
>     365             array.data,
>     366             parents.data,
>     367             parents.length,
>     368             outlength,
>     369         )
>     370     )
>     371 elif result.dtype in (np.int32, np.uint32):
>     372     assert parents.nplike is array.backend.index_nplike
> 
> File [~/coffea-gpu/awkward/src/awkward/_kernels.py:169](https://analytics-hub.fnal.gov/user/lagray/lab/tree/coffea-gpu/coffea-gpu/awkward/src/awkward/_kernels.py#line=168), in CupyKernel.__call__(self, *args)
>     157 args = (
>     158     *args,
>     159     len(ak_cuda.cuda_streamptr_to_contexts[cupy_stream_ptr][1]),
>     160     ak_cuda.cuda_streamptr_to_contexts[cupy_stream_ptr][0],
>     161 )
>     162 ak_cuda.cuda_streamptr_to_contexts[cupy_stream_ptr][1].append(
>     163     ak_cuda.Invocation(
>     164         name=self.key[0],
>     165         error_context=ak._errors.ErrorContext.primary(),
>     166     )
>     167 )
> --> 169 self._impl(grid, blocks, args)
> 
> File [~/coffea-gpu/awkward/src/awkward/_connect/cuda/_kernel_signatures.py:4337](https://analytics-hub.fnal.gov/user/lagray/lab/tree/coffea-gpu/coffea-gpu/awkward/src/awkward/_connect/cuda/_kernel_signatures.py#line=4336), in by_signature.<locals>.f(grid, block, args)
>    4335     segment = 0
>    4336     grid_size = 1
> -> 4337 partial = cupy.zeros(outlength * grid_size, dtype=toptr.dtype)
>    4338 temp = cupy.zeros(lenparents, dtype=toptr.dtype)
>    4339 cuda_kernel_templates.get_function(fetch_specialization(["awkward_reduce_sum_int64_bool_64_a", int64, bool_, pa [...]

2024-06-06 14:41 UTC, lgray commented
No worries - just reporting what I'm finding with things as they are. Thanks!

2024-06-06 15:28 UTC, ManasviGoyal commented
> No worries - just reporting what I'm finding with things as they are. Thanks!

Yes. It's very helpful since I can only test of a limited number of cases so knowing how it works for actual data helps in identifying the issues. Thanks! I will keep you updated.

2024-06-07 16:46 UTC, lgray commented
The change to accumulator with atomics certainly fixed the memory issue, it's a bit slower than I expected for a sum though. ~250 MHz throughput for summing bools into int64.  

As an optimization for sums on the last dimension, couldn't you write this without atomics or any race conditions by having each thread sum over the last dimension into an array of one less dimension? Or is the thread divergence too bad and atomics are still faster?

With the atomic implementation you're guaranteed to have access contention because each element is going to be hitting the same output position to make the sum. I don't have good intuition if that's going to be better or worse than thread divergence.

@jpivarski maybe?

2024-06-07 18:38 UTC, lgray commented
In any case - with this latest change I've now got query 4 done on the ADL's. The rest seem to require combinations, so I'll wait for that!

2024-06-11 15:50 UTC, lgray commented
Ah, indeed, looking at how you've implemented atomics, there's already effectively thread divergence built into your kernel. 
So, I think we can get less thread divergence if we drop atomics for sum, when it is along the last axis, which is a very common case worth optimizing.

2024-06-11 21:44 UTC, ManasviGoyal commented
> Ah, indeed, looking at how you've implemented atomics, there's already effectively thread divergence built into your kernel. So, I think we can get less thread divergence if we drop atomics for sum, when it is along the last axis, which is a very common case worth optimizing.

Thanks for the feedback. You are right. The conditions checking for the boundry condition are causing divergence. I will try some other approaches to handle the block boundary case as we need to make sure the sum is carried over across bock for each `parent`. I was thinking of using another reduction step to replace the atomics. I'll update once I have an implementation.

2024-06-11 22:01 UTC, lgray commented
That being said I wouldn't throw the baby out with the bath water and delay merging this if you are otherwise happy. Performance can be won over time.

2024-06-11 22:12 UTC, ManasviGoyal commented
> That being said I wouldn't throw the baby out with the bath water and delay merging this if you are otherwise happy. Performance can be won over time.

Okay, I agree. Then it would be better to finalize and merge this with the current implementation for now. I can work on implementing other important kernels and get back to these once I am done.

2024-06-12 15:11 UTC, ManasviGoyal commented
@ianna Should I close #3123 or can this be merged? This just contains some studies I did for reducers.

2024-06-12 19:53 UTC, ianna reviewed
@ManasviGoyal - I'm not sure if it's a regression or my configuration. Do you see these tests pass?
Thanks!

**tests-cuda-kernels-explicit** 5895 passed in 8.95s
**tests-cuda-kernels** 6448 passed, 193 skipped in 8.06s
**tests-cuda** 48 failed, 522 passed in 12.89s

```
========================================= short test summary info ==========================================
FAILED tests-cuda/test_3140_cuda_jagged_and_masked_getitem.py::test_0111_jagged_and_masked_getitem_bitmaskedarray2b - assert [[0.0, 1.1, 2...e, None, None] == [[0.0, 1.1, 2....7, 8.8, 9.9]]
FAILED tests-cuda/test_3140_cuda_jagged_and_masked_getitem.py::test_0111_jagged_and_masked_getitem_bytemaskedarray2b - assert [[], [], [], []] == [[1.1, 1.1], ...], [6.6, 9.9]]
FAILED tests-cuda/test_3140_cuda_jagged_and_masked_getitem.py::test_0111_jagged_and_masked_getitem_emptyarray - assert [[], [], [], []] == [[], [None], [], []]
FAILED tests-cuda/test_3140_cuda_jagged_and_masked_getitem.py::test_0111_jagged_and_masked_getitem_indexedarray - cupy.cuda.memory.OutOfMemoryError: Out of memory allocating 45,035,996,273,704,960 bytes (allocated so ...
FAILED tests-cuda/test_3140_cuda_jagged_and_masked_getitem.py::test_0111_jagged_and_masked_getitem_indexedarray2 - AssertionError: broadcast_tooffsets64 can only be used with offsets that start at 0, not 257
FAILED tests-cuda/test_3140_cuda_jagged_and_masked_getitem.py::test_0111_jagged_and_masked_getitem_indexedarray2b - cupy.cuda.memory.OutOfMemoryError: Out of memory allocating 34,224,996,864 bytes (allocated so far: 21,...
FAILED tests-cuda/test_3140_cuda_jagged_and_masked_getitem.py::test_0111_jagged_and_masked_getitem_indexedarray3 - assert [4.4, None, 1.1] == [4.4, None, 2.2]
FAILED tests-cuda/test_3140_cuda_jagged_and_masked_getitem.py::test_0111_jagged_and_masked_getitem_jagged - assert [[], [], [], [], []] == [[1.1, 3.3], ....8, 8.8, 7.7]]
FAILED tests-cuda/test_3140_cuda_jagged_and_masked_getitem.py::test_0111_jagged_and_masked_getitem_double_jagged - assert [[], []] == [[[2, 1, 0], ... 10, 10, 12]]]
FAILED tests-cuda/test_3140_cuda_jagged_and_masked_getitem.py::test_0111_jagged_and_masked_getitem_masked_jagged - assert [[], [], [], [], []] == [[3.3, 2.2], ...e, [8.8, 7.7]]
FAILED tests-cuda/test_3140_cuda_jagged_and_masked_getitem.py::test_0111_jagged_and_masked_getitem_jagged_masked - cupy.cuda.memory.OutOfMemoryError: Out of memory allocating 8,796,227,240,448 bytes (allocated so far: ...
FAILED tests-cuda/test_3140_cuda_jagged_and_masked_getitem.py::test_0111_jagged_and_masked_getitem_array_boolean_to_int - assert [[3, -1, 2], ... [0, 0, 0, 0]] == [[0, 1, 2], [... [0, 1, 2, 3]]
FAILED tests-cuda/test_3140_cuda_jagged_and_masked_getitem.py::test_0111_jagged_and_masked_getitem_array_slice - assert [0.0, 2.2, 2....5.5, 9.9, ...] == [5.5, 2.2, 2....9.9, 0.0, ...]
FAILED tests-cuda/test_3140_cuda_jagged_and_masked_getitem.py::test_0111_jagged_and_masked_getitem_jagged_mask - assert [[], [], [], [], []] == [[1.1, 2.2, 3....7, 8.8, 9.9]]
FAILED tests-cuda/test_3140_cuda_jagged_and_masked_getitem.py::test_0111_jagged_and_masked_getitem_jagged_missing_mask - assert [[], [], [1.1, 1.1, 1.1]] == [[1.1, 2.2, 3...], [4.4, 5.5]]
FAILED tests-cuda/test_3140_cuda_jagged_and_masked_getitem.py::test_0111_jagged_and_masked_getitem_masked_of_jagged_of_whatever - ValueError: Negative dimensions are not allowed
FAILED tests-cuda/test_3140_cuda_jagged_and_masked_getitem.py::test_0111_jagged_and_masked_getitem_missing - assert [3.3, 3.3, 3.3, 3.3, 3.3, 3.3] == [3.3, 6.6, No...one, 8.8, 6.6]
FAILED tests-cuda/test_3140_cuda_jagged_and_masked_getitem.py::test_0111_jagged_and_masked_getitem_new_slices - assert [1, 0, None, 9, 3, None, ...] == [5, 2, None, 3, 9, None, ...]
FAILED tests-cuda/test_3140_cuda_jagged_and_masked_getitem.py::test_0111_jagged_and_masked_getitem_record - ValueError: Negative dimensions are not allowed
FAILED tests-cuda/test_3140_cuda_jagged_and_masked_getitem.py::test_0111_jagged_and_masked_getitem_records_missing - AssertionError: assert [{'x': 3, 'y'... 0, 'y': 0.0}] == [{'x': 3, 'y'... 7, 'y': 7.7}]
FAILED tests-cuda/test_3140_cuda_jagged_and_masked_getitem.py::test_0111_jagged_and_masked_getitem_regular_regular - assert [[[], [], [], [], []], []] == [[[2], [6, 8]...[25, 27, 29]]]
FAILED tests-cuda/test_3140_cuda_jagged_and_masked_getitem.py::test_0111_jagged_and_masked_getitem_sequential - assert [[], []] == [[[10, 11, 12... 17, 18, 19]]]
FAILED tests-cuda/test_3140_cuda_jagged_and_masked_getitem.py::test_0111_jagged_and_masked_getitem_union_2 - assert [[], [], [], [], [], [], ...] == [[1.1, 3.3], ...8.8], [], ...]
FAILED tests-cuda/test_3140_cuda_slicing.py::test_0315_integerindex_null_more - ValueError: Negative dimensions are not allowed
FAILED tests-cuda/test_3140_cuda_slicing.py::test_0315_integerindex_null_more_2 - ValueError: Negative dimensions are not allowed
FAILED tests-cuda/test_3140_cuda_slicing.py::test_1405_slicing_untested_cases_list_option_list - IndexError: cannot slice ListArray (of length 0) with [[], [0]]: cannot fit jagged slice with length 2 ...
FAILED tests-cuda/test_3140_cuda_slicing.py::test_1405_slicing_untested_cases_list_option_list_offset - IndexError: cannot slice ListArray (of length 0) with [[], [0]]: cannot fit jagged slice with length 2 ...
FAILED tests-cuda/test_3140_cuda_slicing.py::test_1502_getitem_jagged_issue1406 - IndexError: cannot slice ListArray (of length 0) with [[], [0]]: cannot fit jagged slice with length 2 ...
FAILED tests-cuda/test_3140_cuda_slicing.py::test_1502_getitem_jagged_issue1406_success_start_offset0 - IndexError: cannot slice ListArray (of length 0) with [[], [0]]: cannot fit jagged slice with length 2 ...
FAILED tests-cuda/test_3140_cuda_slicing.py::test_1502_getitem_jagged_issue1406_success_remove_option_type - assert [[[], []]] == [[[], [2]]]
FAILED tests-cuda/test_3140_cuda_slicing.py::test_1502_getitem_jagged_issue1406_success_nonempty_list - IndexError: cannot slice ListArray (of length 128) with [[0], [0]]: cannot fit jagged slice with length...
FAILED tests-cuda/test_3140_cuda_slicing.py::test_1904_drop_none_ListArray_and_axis_None - AssertionError: broadcast_tooffsets64 can only be used with offsets that start at 0, not 1
FAILED tests-cuda/test_3140_cuda_slicing.py::test_1904_drop_none_ListOffsetArray_IndexedOptionArray_NumpyArray_outoforder - assert [[6.6, None, ... [4.4], [4.4]] == [[0.0, None, ... [4.4], [2.2]]
FAILED tests-cuda/test_3140_cuda_slicing.py::test_1904_drop_none_from_iter - assert [[], []] == [[1], [2]]
FAILED tests-cuda/test_3140_cuda_slicing.py::test_1904_drop_none_List_ByteMaskedArray_NumpyArray - ValueError: Negative dimensions are not allowed
FAILED tests-cuda/test_3140_cuda_slicing.py::test_1904_drop_none_RegularArray_RecordArray_NumpyArray - assert [[[3.3, None,....6, 7.7], []]] == [[[0.0, None,....7, 8.8], []]]
FAILED tests-cuda/test_3140_cuda_slicing.py::test_1904_drop_none_RecordArray - ValueError: Negative dimensions are not allowed
FAILED tests-cuda/test_3140_cuda_slicing.py::test_2246_slice_not_packed - assert [[], []] == [[0], [3, 4]]
FAILED tests-cuda/test_3140_cuda_slicing.py::test_0127_tomask_operation_ByteMaskedArray_jaggedslice0 - assert [[], [], [], []] == [[0.0, 1.1, 2....7, 8.8, 9.9]]
FAILED tests-cuda/test_3140_cuda_slicing.py::test_0127_tomask_operation_ByteMaskedArray_jaggedslice1 - assert [[], [], [], [], []] == [[2.2, None, ..., [7.7, None]]
FAILED tests-cuda/test_3140_cuda_slicing.py::test_0127_tomask_operation_ByteMaskedArray_jaggedslice2 - ValueError: Negative dimensions are not allowed
FAILED tests-cuda/test_3140_cuda_slicing.py::test_0127_tomask_operation_ByteMaskedArray_jaggedslice3 - assert [[[[]], [[]], [[]]], [[[]]]] == [[[[2.2, None...[7.7, None]]]]
FAILED tests-cuda/test_3140_cuda_slicing.py::test_0127_tomask_operation - assert [[3.3, 0.0, 6...0], [], [0.0]] == [[0.0, 1.1, 2....7, 8.8, 9.9]]
FAILED tests-cuda/test_3141_cuda_misc.py::test_0150_ByteMaskedArray_flatten - assert [[1.1, 12.2, ...3], [], [4.4] [...]

2024-06-13 03:25 UTC, ManasviGoyal commented
> @ManasviGoyal - I'm not sure if it's a regression or my configuration. Do you see these tests pass? Thanks!
> 
> **tests-cuda-kernels-explicit** 5895 passed in 8.95s **tests-cuda-kernels** 6448 passed, 193 skipped in 8.06s **tests-cuda** 48 failed, 522 passed in 12.89s
> 
> ```
> ========================================= short test summary info ==========================================
> FAILED tests-cuda/test_3140_cuda_jagged_and_masked_getitem.py::test_0111_jagged_and_masked_getitem_bitmaskedarray2b - assert [[0.0, 1.1, 2...e, None, None] == [[0.0, 1.1, 2....7, 8.8, 9.9]]
> FAILED tests-cuda/test_3140_cuda_jagged_and_masked_getitem.py::test_0111_jagged_and_masked_getitem_bytemaskedarray2b - assert [[], [], [], []] == [[1.1, 1.1], ...], [6.6, 9.9]]
> FAILED tests-cuda/test_3140_cuda_jagged_and_masked_getitem.py::test_0111_jagged_and_masked_getitem_emptyarray - assert [[], [], [], []] == [[], [None], [], []]
> FAILED tests-cuda/test_3140_cuda_jagged_and_masked_getitem.py::test_0111_jagged_and_masked_getitem_indexedarray - cupy.cuda.memory.OutOfMemoryError: Out of memory allocating 45,035,996,273,704,960 bytes (allocated so ...
> FAILED tests-cuda/test_3140_cuda_jagged_and_masked_getitem.py::test_0111_jagged_and_masked_getitem_indexedarray2 - AssertionError: broadcast_tooffsets64 can only be used with offsets that start at 0, not 257
> FAILED tests-cuda/test_3140_cuda_jagged_and_masked_getitem.py::test_0111_jagged_and_masked_getitem_indexedarray2b - cupy.cuda.memory.OutOfMemoryError: Out of memory allocating 34,224,996,864 bytes (allocated so far: 21,...
> FAILED tests-cuda/test_3140_cuda_jagged_and_masked_getitem.py::test_0111_jagged_and_masked_getitem_indexedarray3 - assert [4.4, None, 1.1] == [4.4, None, 2.2]
> FAILED tests-cuda/test_3140_cuda_jagged_and_masked_getitem.py::test_0111_jagged_and_masked_getitem_jagged - assert [[], [], [], [], []] == [[1.1, 3.3], ....8, 8.8, 7.7]]
> FAILED tests-cuda/test_3140_cuda_jagged_and_masked_getitem.py::test_0111_jagged_and_masked_getitem_double_jagged - assert [[], []] == [[[2, 1, 0], ... 10, 10, 12]]]
> FAILED tests-cuda/test_3140_cuda_jagged_and_masked_getitem.py::test_0111_jagged_and_masked_getitem_masked_jagged - assert [[], [], [], [], []] == [[3.3, 2.2], ...e, [8.8, 7.7]]
> FAILED tests-cuda/test_3140_cuda_jagged_and_masked_getitem.py::test_0111_jagged_and_masked_getitem_jagged_masked - cupy.cuda.memory.OutOfMemoryError: Out of memory allocating 8,796,227,240,448 bytes (allocated so far: ...
> FAILED tests-cuda/test_3140_cuda_jagged_and_masked_getitem.py::test_0111_jagged_and_masked_getitem_array_boolean_to_int - assert [[3, -1, 2], ... [0, 0, 0, 0]] == [[0, 1, 2], [... [0, 1, 2, 3]]
> FAILED tests-cuda/test_3140_cuda_jagged_and_masked_getitem.py::test_0111_jagged_and_masked_getitem_array_slice - assert [0.0, 2.2, 2....5.5, 9.9, ...] == [5.5, 2.2, 2....9.9, 0.0, ...]
> FAILED tests-cuda/test_3140_cuda_jagged_and_masked_getitem.py::test_0111_jagged_and_masked_getitem_jagged_mask - assert [[], [], [], [], []] == [[1.1, 2.2, 3....7, 8.8, 9.9]]
> FAILED tests-cuda/test_3140_cuda_jagged_and_masked_getitem.py::test_0111_jagged_and_masked_getitem_jagged_missing_mask - assert [[], [], [1.1, 1.1, 1.1]] == [[1.1, 2.2, 3...], [4.4, 5.5]]
> FAILED tests-cuda/test_3140_cuda_jagged_and_masked_getitem.py::test_0111_jagged_and_masked_getitem_masked_of_jagged_of_whatever - ValueError: Negative dimensions are not allowed
> FAILED tests-cuda/test_3140_cuda_jagged_and_masked_getitem.py::test_0111_jagged_and_masked_getitem_missing - assert [3.3, 3.3, 3.3, 3.3, 3.3, 3.3] == [3.3, 6.6, No...one, 8.8, 6.6]
> FAILED tests-cuda/test_3140_cuda_jagged_and_masked_getitem.py::test_0111_jagged_and_masked_getitem_new_slices - assert [1, 0, None, 9, 3, None, ...] == [5, 2, None, 3, 9, None, ...]
> FAILED tests-cuda/test_3140_cuda_jagged_and_masked_getitem.py::test_0111_jagged_and_masked_getitem_record - ValueError: Negative dimensions are not allowed
> FAILED tests-cuda/test_3140_cuda_jagged_and_masked_getitem.py::test_0111_jagged_and_masked_getitem_records_missing - AssertionError: assert [{'x': 3, 'y'... 0, 'y': 0.0}] == [{'x': 3, 'y'... 7, 'y': 7.7}]
> FAILED tests-cuda/test_3140_cuda_jagged_and_masked_getitem.py::test_0111_jagged_and_masked_getitem_regular_regular - assert [[[], [], [], [], []], []] == [[[2], [6, 8]...[25, 27, 29]]]
> FAILED tests-cuda/test_3140_cuda_jagged_and_masked_getitem.py::test_0111_jagged_and_masked_getitem_sequential - assert [[], []] == [[[10, 11, 12... 17, 18, 19]]]
> FAILED tests-cuda/test_3140_cuda_jagged_and_masked_getitem.py::test_0111_jagged_and_masked_getitem_union_2 - assert [[], [], [], [], [], [], ...] == [[1.1, 3.3], ...8.8], [], ...]
> FAILED tests-cuda/test_3140_cuda_slicing.py::test_0315_integerindex_null_more - ValueError: Negative dimensions are not allowed
> FAILED tests-cuda/test_3140_cuda_slicing.py::test_0315_integerindex_null_more_2 - ValueError: Negative dimensions are not allowed
> FAILED tests-cuda/test_3140_cuda_slicing.py::test_1405_slicing_untested_cases_list_option_list - IndexError: cannot slice ListArray (of length 0) with [[], [0]]: cannot fit jagged slice with length 2 ...
> FAILED tests-cuda/test_3140_cuda_slicing.py::test_1405_slicing_untested_cases_list_option_list_offset - IndexError: cannot slice ListArray (of length 0) with [[], [0]]: cannot fit jagged slice with length 2 ...
> FAILED tests-cuda/test_3140_cuda_slicing.py::test_1502_getitem_jagged_issue1406 - IndexError: cannot slice ListArray (of length 0) with [[], [0]]: cannot fit jagged slice with length 2 ...
> FAILED tests-cuda/test_3140_cuda_slicing.py::test_1502_getitem_jagged_issue1406_success_start_offset0 - IndexError: cannot slice ListArray (of length 0) with [[], [0]]: cannot fit jagged slice with length 2 ...
> FAILED tests-cuda/test_3140_cuda_slicing.py::test_1502_getitem_jagged_issue1406_success_remove_option_type - assert [[[], []]] == [[[], [2]]]
> FAILED tests-cuda/test_3140_cuda_slicing.py::test_1502_getitem_jagged_issue1406_success_nonempty_list - IndexError: cannot slice ListArray (of length 128) with [[0], [0]]: cannot fit jagged slice with length...
> FAILED tests-cuda/test_3140_cuda_slicing.py::test_1904_drop_none_ListArray_and_axis_None - AssertionError: broadcast_tooffsets64 can only be used with offsets that start at 0, not 1
> FAILED tests-cuda/test_3140_cuda_slicing.py::test_1904_drop_none_ListOffsetArray_IndexedOptionArray_NumpyArray_outoforder - assert [[6.6, None, ... [4.4], [4.4]] == [[0.0, None, ... [4.4], [2.2]]
> FAILED tests-cuda/test_3140_cuda_slicing.py::test_1904_drop_none_from_iter - assert [[], []] == [[1], [2]]
> FAILED tests-cuda/test_3140_cuda_slicing.py::test_1904_drop_none_List_ByteMaskedArray_NumpyArray - ValueError: Negative dimensions are not allowed
> FAILED tests-cuda/test_3140_cuda_slicing.py::test_1904_drop_none_RegularArray_RecordArray_NumpyArray - assert [[[3.3, None,....6, 7.7], []]] == [[[0.0, None,....7, 8.8], []]]
> FAILED tests-cuda/test_3140_cuda_slicing.py::test_1904_drop_none_RecordArray - ValueError: Negative dimensions are not allowed
> FAILED tests-cuda/test_3140_cuda_slicing.py::test_2246_slice_not_packed - assert [[], []] == [[0], [3, 4]]
> FAILED tests-cuda/test_3140_cuda_slicing.py::test_0127_tomask_operation_ByteMaskedArray_jaggedslice0 - assert [[], [], [], []] == [[0.0, 1.1, 2....7, 8.8, 9.9]]
> FAILED tests-cuda/test_3140_cuda_slicing.py::test_0127_tomask_operation_ByteMaskedArray_jaggedslice1 - assert [[], [], [], [], []] == [[2.2, None, ..., [7.7, None]]
> FAILED tests-cuda/test_3140_cuda_slicing.py::test_0127_tomask_operation_ByteMaskedArray_jaggedslice2 - ValueError: Negative dimensions are not allowed
> FAILED tests-cuda/test_3140_cuda_slicing.py::test_0127_tomask_operation_ByteMaskedArray_jaggedslice3 - assert [[[[]], [[]], [[]]], [[[]]]] == [[[[2.2, None...[7.7, None]]]]
> FAILED tests-cuda/test_3140_cuda_slicing.py::test_0127_tomask_operation - assert [[3.3, 0.0, 6...0], [], [0.0]] == [[0.0, 1.1, 2....7, 8.8, 9.9]]
> FAILED tests-c [...]

2024-06-13 10:09 UTC, ianna reviewed
@ManasviGoyal - please, check it on Monday as agreed.

2024-06-13 10:09 UTC, ianna commented on tests-cuda/test_3136_cuda_reducers.py
> +    # out3 = ak.std(array[2], axis=None, mask_identity=True)
@ManasviGoyal - I don't know why but this line causes all subsequent tests to fail.

2024-06-18 15:58 UTC, ManasviGoyal commented on tests-cuda/test_3136_cuda_reducers.py
> +    # out3 = ak.std(array[2], axis=None, mask_identity=True)
@ianna I have fixed the issue. It was caused to to a `TypeTracer` array not being passed correctly for `cuda` backend.

unrelated to this PR, I saw that several `tests-spec-explicit` were failing which I fixed but there is still a couple of non kernel tests that are failing(even for other PRs).

2024-06-18 16:18 UTC, ianna commented on tests-cuda/test_3136_cuda_reducers.py
> +    # out3 = ak.std(array[2], axis=None, mask_identity=True)
Thanks! I will have a look at it

2024-06-18 19:25 UTC, ianna commented on tests-cuda/test_3136_cuda_reducers.py
> +    # out3 = ak.std(array[2], axis=None, mask_identity=True)
```
__________________________ test_sumprod_types_FIXME ___________________________

    def test_sumprod_types_FIXME():
        array = np.array([[True, False, False], [True, False, False]])
        content2 = ak.contents.NumpyArray(array.reshape(-1))
        offsets3 = ak.index.Index64(np.array([0, 3, 3, 5, 6], dtype=np.int64))
        depth1 = ak.contents.ListOffsetArray(offsets3, content2)
>       assert (
            np.sum(array, axis=-1).dtype
            == ak.to_numpy(ak.sum(depth1, axis=-1, highlevel=False)).dtype
        )
E       AssertionError: assert dtype('int32') == dtype('int64')
```

2024-06-19 08:56 UTC, ManasviGoyal commented on tests-cuda/test_3136_cuda_reducers.py
> +    # out3 = ak.std(array[2], axis=None, mask_identity=True)
I was referring to this error only. But this looks irrelevant to this PR as the same test is failing for other PRs too.

2024-06-19 09:31 UTC, ianna commented on tests-cuda/test_3136_cuda_reducers.py
> +    # out3 = ak.std(array[2], axis=None, mask_identity=True)
There are two tests failing on `dtype` comparison on boolean arrays sum. It looks like `numpy` may use `int32` for sum operations on boolean arrays, depending on the platform (32-bit vs 64-bit).

2024-06-19 09:38 UTC, ianna approved these changes
I do not see any changes in this PR that would cause the test failures or causing `numpy` to use `int32` for sum operations on boolean arrays (depending on the platform (32-bit vs 64-bit)). 

We could explicitly cast the result of numpy sum to int64 to ensure the test doesn't fail:

`numpy_sum = np.sum(array, axis=-1).astype(np.int64) 
`

I'd say merge it - @jpivarski?

2024-06-19 09:48 UTC, ianna commented
I'm checking it with https://github.com/scikit-hep/awkward/pull/3158

2024-06-19 10:26 UTC, ianna commented
> I'm checking it with #3158
and https://github.com/scikit-hep/awkward/pull/3159

I've opened an issue: https://github.com/scikit-hep/awkward/issues/3160

2024-06-19 14:59 UTC, jpivarski approved these changes
This is excellent!!! As I understand it, this enables all `axis=-1` reducers, with tests for crossing block boundaries. As we talked about in our meeting, it could have more tests of block boundary crossing and integration tests (converted from `tests` to `tests-cuda`, particularly `test_0115_generic_reducer_operation.py`).

The one failing test is unrelated, and it's failing in `main` also, so it isn't a blocker to merging this PR. (We should never _introduce_ failing tests into `main`, but it's already there. @ianna, if you need elevated permissions to bypass the red warning about merging with a failing test, I can give you those permissions.)

What is a blocker, however, is that these need to be tested on more than one GPU. @ianna will be able to test it on Sunday, and it can be merged if it passes on her GPU. I'll be able to test it on Tuesday, and I'll just test it in `main` (after merging).

2024-06-24 08:56 UTC, ianna requested changes
@ManasviGoyal - all tests pass except for the `tests-cuda-kernels/test_cudaawkward_BitMaskedArray_to_ByteMaskedArray.py` that relies on `Numpy`. I've added an import. Please, double check. Thanks!

2024-06-24 08:56 UTC, ianna commented on dev/generate-tests.py
> +                    "import cupy.testing as cpt\n"
```suggestion
                    "import cupy.testing as cpt\n"
                    "import numpy as np\n"
```

2024-06-24 09:06 UTC, ianna approved these changes
@ManasviGoyal - all tests pass on my local computer with the updated branch with the import of `numpy`! If it works fine on yours the PR is good to be merged. Thanks.

2024-06-24 10:22 UTC, ManasviGoyal commented
> @ManasviGoyal - all tests pass on my local computer with the updated branch with the import of `numpy`! If it works fine on yours the PR is good to be merged. Thanks.

@ianna All MacOS tests are cancelled in the CI due to which I am unable to merge.

2024-06-24 12:27 UTC, ianna commented
@jpivarski - I think, we need some other macOS node:

<div><svg class="octicon octicon-x-circle-fill mr-2 color-fg-danger" viewBox="0 0 16 16" version="1.1" width="16" height="16" aria-hidden="true"></svg></div>
Run Tests (macos-11, 3.8, x64, full)                                                                                                                           This is a scheduled macOS-11 brownout. The macOS-11 environment is deprecated and will be removed on June 28th, 2024.
--
 

2024-06-24 15:09 UTC, ManasviGoyal commented
> This is excellent!!! As I understand it, this enables all `axis=-1` reducers, with tests for crossing block boundaries. As we talked about in our meeting, it could have more tests of block boundary crossing and integration tests (converted from `tests` to `tests-cuda`, particularly `test_0115_generic_reducer_operation.py`).

@jpivarski #3162 adds all the `axis=-1` tests in `test_0115_generic_reducer_operation.py` for cuda. I have also added tests to check for block boundary for array size = 3000 (primes for `ak.prod`) as we discussed in the last meeting. Thanks!

2024-06-25 15:30 UTC, jpivarski approved these changes
@ianna and I have both tested with GPUs and all is good, so I'll merge this now. (Before June 28, we avoid complications with MacOS > 11.)

2024-06-25 15:30 UTC, merged